In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Imported libraries together to be cleaner and streamlined. Running basic head, info, value counts, and describe to see where to start on data cleanup.

In [3]:
df = pd.read_csv('sleep_mobile_stress_dataset_15000.csv')
df.head()

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
0,1,56,Female,Designer,3.26,86,5.31,7.72,3.49,0,35,119,3.57
1,2,46,Female,Teacher,1.85,32,7.36,9.70,3.01,0,16,299,1.91
2,3,32,Female,Designer,3.04,107,4.50,6.38,5.03,0,17,21,6.05
3,4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92
4,5,38,Female,Teacher,3.52,56,7.57,6.69,6.71,4,92,167,5.99

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           15000 non-null  int64
 1   age                               15000 non-null  int64
 2   gender                            15000 non-null  str
 3   occupation                        15000 non-null  str
 4   daily_screen_time_hours           15000 non-null  float64
 5   phone_usage_before_sleep_minutes  15000 non-null  int64
 6   sleep_duration_hours              15000 non-null  float64
 7   sleep_quality_score               15000 non-null  float64
 8   stress_level                      15000 non-null  float64
 9   caffeine_intake_cups              15000 non-null  int64
 10  physical_activity_minutes         15000 non-null  int64
 11  notifications_received_per_day    15000 non-null  int64
 12  mental_fatigue_score              15000 non-null  float64
dtypes: float64(5), int64(6), str(2)
memory usage: 1.5 MB

In [4]:
df.value_counts()

user_id  age  gender  occupation         daily_screen_time_hours  phone_usage_before_sleep_minutes  sleep_duration_hours  sleep_quality_score  stress_level  caffeine_intake_cups  physical_activity_minutes  notifications_received_per_day  mental_fatigue_score
1        56   Female  Designer           3.26                     86                                5.31                  7.72                 3.49          0                     35                         119                             3.57                    1
2        46   Female  Teacher            1.85                     32                                7.36                  9.70                 3.01          0                     16                         299                             1.91                    1
3        32   Female  Designer           3.04                     107                               4.50                  6.38                 5.03          0                     17                         21                              6.05                    1
4        25   Male    Software Engineer  9.00                     36                                6.68                  5.53                 10.00         0                     3                          220                             9.92                    1
5        38   Female  Teacher            3.52                     56                                7.57                  6.69                 6.71          4                     92                         167                             5.99                    1
                                                                                                                                                                                                                                                                     ..
14996    39   Male    Manager            8.05                     45                                8.91                  4.33                 10.00         1                     40                         259                             10.00                   1
14997    22   Female  Student            6.44                     80                                6.00                  5.22                 10.00         2                     41                         231                             7.54                    1
14998    51   Female  Software Engineer  7.01                     78                                7.27                  5.37                 8.66          4                     93                         288                             7.78                    1
14999    56   Female  Software Engineer  7.89                     6                                 5.70                  5.71                 9.56          1                     91                         47                              9.98                    1
15000    20   Female  Freelancer         6.05                     93                                4.74                  5.04                 9.33          0                     117                        64                              9.26                    1
Name: count, Length: 15000, dtype: int64

In [5]:
df.describe()

,user_id,age,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.00000,15000.000000,15000.000000,15000.000000
mean,7500.500000,38.488467,5.501528,59.708933,6.509683,6.246362,6.980247,1.99880,59.157133,160.890467,6.873009
std,4330.271354,12.007970,2.600085,34.641858,1.452689,1.713644,2.749382,1.41459,34.525705,80.856902,2.730482
min,1.000000,18.000000,1.000000,0.000000,4.000000,1.000000,1.000000,0.00000,0.000000,20.000000,1.000000
25%,3750.750000,28.000000,3.260000,29.000000,5.260000,5.000000,4.750000,1.00000,29.000000,92.000000,4.700000
50%,7500.500000,38.000000,5.490000,60.000000,6.490000,6.250000,7.380000,2.00000,59.000000,162.000000,7.380000
75%,11250.250000,49.000000,7.760000,90.000000,7.790000,7.500000,10.000000,3.00000,89.000000,231.000000,9.450000
max,15000.000000,59.000000,10.000000,119.000000,9.000000,10.000000,10.000000,4.00000,119.000000,299.000000,10.000000

In [6]:
df['caffeine_intake_cups'].value_counts()

caffeine_intake_cups
0    3006
1    3000
4    2998
2    2998
3    2998
Name: count, dtype: int64

First instance where data is evenly spread between options, shows the reality that this is a synthetic dataset.

In [7]:
df.duplicated().value_counts()

False    15000
Name: count, dtype: int64

In [8]:
df['age'].value_counts().sort_index()

age
18    338
19    360
20    350
21    355
22    338
23    351
24    328
25    363
26    348
27    346
28    331
29    354
30    396
31    359
32    376
33    376
34    398
35    371
36    368
37    350
38    369
39    375
40    386
41    358
42    352
43    403
44    326
45    385
46    366
47    334
48    323
49    356
50    352
51    338
52    353
53    351
54    365
55    345
56    364
57    344
58    340
59    359
Name: count, dtype: int64

The data is evenly spread out along 18-59 year olds. No strong outliers or significantly different amounts.

In [9]:
null_rows = df[df['occupation'].isna()]
print(null_rows)

Empty DataFrame
Columns: [user_id, age, gender, occupation, daily_screen_time_hours, phone_usage_before_sleep_minutes, sleep_duration_hours, sleep_quality_score, stress_level, caffeine_intake_cups, physical_activity_minutes, notifications_received_per_day, mental_fatigue_score]
Index: []

In [10]:
df.shape

(15000, 13)

In [11]:
df.columns

Index(['user_id', 'age', 'gender', 'occupation', 'daily_screen_time_hours',
       'phone_usage_before_sleep_minutes', 'sleep_duration_hours',
       'sleep_quality_score', 'stress_level', 'caffeine_intake_cups',
       'physical_activity_minutes', 'notifications_received_per_day',
       'mental_fatigue_score'],
      dtype='str')

15000 rows and list of columns. This information will be useful with database creation.

In [12]:
df.value_counts('gender')
df.value_counts('occupation')

occupation
Manager              1962
Doctor               1922
Software Engineer    1917
Freelancer           1891
Student              1861
Researcher           1837
Designer             1813
Teacher              1797
Name: count, dtype: int64

In [13]:
df_subset = df[['sleep_quality_score', 'stress_level']]
print(df_subset)

       sleep_quality_score  stress_level
0                     7.72          3.49
1                     9.70          3.01
2                     6.38          5.03
3                     5.53         10.00
4                     6.69          6.71
...                    ...           ...
14995                 4.33         10.00
14996                 5.22         10.00
14997                 5.37          8.66
14998                 5.71          9.56
14999                 5.04          9.33

[15000 rows x 2 columns]

Creating a function to automatically average a numerical column that is grouped by a string column.

In [4]:
##Function 1
def average_by_group(df, group_col, value_col):
        return df.groupby(group_col)[value_col].mean().sort_values(ascending=False)

In [5]:
average_by_group(df, "gender","stress_level")

gender
Other     7.100650
Male      6.999816
Female    6.950724
Name: stress_level, dtype: float64

Average stress level for all 3 gender categories are extremely close. Averages are within plus or minus 0.2. Would like to add min and max to the function as well.

In [9]:
##Function 1
def summary_by_group(df, group_col, value_col):
        return df.groupby(group_col)[value_col].agg(['min','mean', 'max'])

In [7]:
average_by_group(df, "occupation", "daily_screen_time_hours")

occupation
Student              5.634970
Software Engineer    5.550402
Manager              5.543012
Doctor               5.492612
Teacher              5.469950
Researcher           5.455237
Designer             5.451655
Freelancer           5.409471
Name: daily_screen_time_hours, dtype: float64

In [10]:
summary_by_group(df, 'occupation', 'daily_screen_time_hours')

                    min      mean    max
occupation
Designer           1.01  5.451655  10.00
Doctor             1.00  5.492612  10.00
Freelancer         1.00  5.409471   9.99
Manager            1.00  5.543012  10.00
Researcher         1.01  5.455237  10.00
Software Engineer  1.01  5.550402  10.00
Student            1.00  5.634970   9.99
Teacher            1.01  5.469950   9.97

This is rough. Shows how even the snthetic data is, evenly spread min, mean, and max

Create a function that will make a column categorizing the screen time into low, moderate, and high groups based off of the numerical value of daily_screen_time_hours.

In [12]:
##function 2
def screen_time_category(hours):
        if hours < 3:
                return "Low"
        elif hours < 6:
                return "Moderate"
        else:
                return "High"

In [13]:
df['screen_time_category'] = df['daily_screen_time_hours'].apply(screen_time_category)

In [14]:
df[['daily_screen_time_hours', 'screen_time_category']].head(10)

   daily_screen_time_hours screen_time_category
0                     3.26             Moderate
1                     1.85                  Low
2                     3.04             Moderate
3                     9.00                 High
4                     3.52             Moderate
5                     7.26                 High
6                     4.56             Moderate
7                     3.36             Moderate
8                     2.30                  Low
9                     9.75                 High

Check to see if new column is added to dataset.

In [20]:
df.head(5)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score,screen_time_category
0,1,56,Female,Designer,3.26,86,5.31,7.72,3.49,0,35,119,3.57,Moderate
1,2,46,Female,Teacher,1.85,32,7.36,9.70,3.01,0,16,299,1.91,Low
2,3,32,Female,Designer,3.04,107,4.50,6.38,5.03,0,17,21,6.05,Moderate
3,4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92,High
4,5,38,Female,Teacher,3.52,56,7.57,6.69,6.71,4,92,167,5.99,Moderate

In [21]:
df.shape

(15000, 14)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           15000 non-null  int64
 1   age                               15000 non-null  int64
 2   gender                            15000 non-null  str
 3   occupation                        15000 non-null  str
 4   daily_screen_time_hours           15000 non-null  float64
 5   phone_usage_before_sleep_minutes  15000 non-null  int64
 6   sleep_duration_hours              15000 non-null  float64
 7   sleep_quality_score               15000 non-null  float64
 8   stress_level                      15000 non-null  float64
 9   caffeine_intake_cups              15000 non-null  int64
 10  physical_activity_minutes         15000 non-null  int64
 11  notifications_received_per_day    15000 non-null  int64
 12  mental_fatigue_score              15000 non-null  float64
 13  screen_time_category              15000 non-null  str
dtypes: float64(5), int64(6), str(3)
memory usage: 1.6 MB

YES! It added the new column and has no nulls.

In [23]:
df.isnull().sum()

user_id                             0
age                                 0
gender                              0
occupation                          0
daily_screen_time_hours             0
phone_usage_before_sleep_minutes    0
sleep_duration_hours                0
sleep_quality_score                 0
stress_level                        0
caffeine_intake_cups                0
physical_activity_minutes           0
notifications_received_per_day      0
mental_fatigue_score                0
screen_time_category                0
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

Check to make sure user id is unique.

In [25]:
df['user_id'].is_unique

True

In [26]:
df.describe()

,user_id,age,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.00000,15000.000000,15000.000000,15000.000000
mean,7500.500000,38.488467,5.501528,59.708933,6.509683,6.246362,6.980247,1.99880,59.157133,160.890467,6.873009
std,4330.271354,12.007970,2.600085,34.641858,1.452689,1.713644,2.749382,1.41459,34.525705,80.856902,2.730482
min,1.000000,18.000000,1.000000,0.000000,4.000000,1.000000,1.000000,0.00000,0.000000,20.000000,1.000000
25%,3750.750000,28.000000,3.260000,29.000000,5.260000,5.000000,4.750000,1.00000,29.000000,92.000000,4.700000
50%,7500.500000,38.000000,5.490000,60.000000,6.490000,6.250000,7.380000,2.00000,59.000000,162.000000,7.380000
75%,11250.250000,49.000000,7.760000,90.000000,7.790000,7.500000,10.000000,3.00000,89.000000,231.000000,9.450000
max,15000.000000,59.000000,10.000000,119.000000,9.000000,10.000000,10.000000,4.00000,119.000000,299.000000,10.000000

In [27]:
df['user_id'].head()

0    1
1    2
2    3
3    4
4    5
Name: user_id, dtype: int64

Add D2 as prefix to user id to differentiate easier between user ids from Dataset 1 and Dataset 2 in database.

In [28]:
df['user_id'] = 'D2_' + df['user_id'].astype(str)

In [29]:
df.head(5)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score,screen_time_category
0,D2_1,56,Female,Designer,3.26,86,5.31,7.72,3.49,0,35,119,3.57,Moderate
1,D2_2,46,Female,Teacher,1.85,32,7.36,9.70,3.01,0,16,299,1.91,Low
2,D2_3,32,Female,Designer,3.04,107,4.50,6.38,5.03,0,17,21,6.05,Moderate
3,D2_4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92,High
4,D2_5,38,Female,Teacher,3.52,56,7.57,6.69,6.71,4,92,167,5.99,Moderate

I messed up and added d1 and d2 to the 2nd dataset. I need to replace D2_D1_ with just D2_ prefix.

In [30]:
df['user_id'] = df['user_id'].str.replace('D2_D1_', "D2_", regex=False)

In [31]:
df.head(5)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score,screen_time_category
0,D2_1,56,Female,Designer,3.26,86,5.31,7.72,3.49,0,35,119,3.57,Moderate
1,D2_2,46,Female,Teacher,1.85,32,7.36,9.70,3.01,0,16,299,1.91,Low
2,D2_3,32,Female,Designer,3.04,107,4.50,6.38,5.03,0,17,21,6.05,Moderate
3,D2_4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92,High
4,D2_5,38,Female,Teacher,3.52,56,7.57,6.69,6.71,4,92,167,5.99,Moderate

User Id prefix is corrected.

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           15000 non-null  str
 1   age                               15000 non-null  int64
 2   gender                            15000 non-null  str
 3   occupation                        15000 non-null  str
 4   daily_screen_time_hours           15000 non-null  float64
 5   phone_usage_before_sleep_minutes  15000 non-null  int64
 6   sleep_duration_hours              15000 non-null  float64
 7   sleep_quality_score               15000 non-null  float64
 8   stress_level                      15000 non-null  float64
 9   caffeine_intake_cups              15000 non-null  int64
 10  physical_activity_minutes         15000 non-null  int64
 11  notifications_received_per_day    15000 non-null  int64
 12  mental_fatigue_score              15000 non-null  float64
 13  screen_time_category              15000 non-null  str
dtypes: float64(5), int64(5), str(4)
memory usage: 1.6 MB

Similar to function 2, create a new column with the rank of users stress level based on numeric values. As of 7/17/26 still unsure if I will be using this as my 3rd function. It is extremely similar to the 2nd function.

In [15]:
#function 3
def stress_level_rank(score):
    if score <= 3.4:
        return "Low"
    elif score >= 6.5:
        return "High"
    else:
        return "Moderate"

In [16]:
df['stress_level_rank'] = df['stress_level'].apply(stress_level_rank)

In [17]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 15 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           15000 non-null  int64
 1   age                               15000 non-null  int64
 2   gender                            15000 non-null  str
 3   occupation                        15000 non-null  str
 4   daily_screen_time_hours           15000 non-null  float64
 5   phone_usage_before_sleep_minutes  15000 non-null  int64
 6   sleep_duration_hours              15000 non-null  float64
 7   sleep_quality_score               15000 non-null  float64
 8   stress_level                      15000 non-null  float64
 9   caffeine_intake_cups              15000 non-null  int64
 10  physical_activity_minutes         15000 non-null  int64
 11  notifications_received_per_day    15000 non-null  int64
 12  mental_fatigue_score              15000 non-null  float64
 13  screen_time_category              15000 non-null  str
 14  stress_level_rank                 15000 non-null  str
dtypes: float64(5), int64(6), str(4)
memory usage: 1.7 MB

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 15 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           15000 non-null  int64
 1   age                               15000 non-null  int64
 2   gender                            15000 non-null  str
 3   occupation                        15000 non-null  str
 4   daily_screen_time_hours           15000 non-null  float64
 5   phone_usage_before_sleep_minutes  15000 non-null  int64
 6   sleep_duration_hours              15000 non-null  float64
 7   sleep_quality_score               15000 non-null  float64
 8   stress_level                      15000 non-null  float64
 9   caffeine_intake_cups              15000 non-null  int64
 10  physical_activity_minutes         15000 non-null  int64
 11  notifications_received_per_day    15000 non-null  int64
 12  mental_fatigue_score              15000 non-null  float64
 13  screen_time_category              15000 non-null  str
 14  stress_level_rank                 15000 non-null  str
dtypes: float64(5), int64(6), str(4)
memory usage: 1.7 MB

In [19]:
df.head(5)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score,screen_time_category,stress_level_rank
0,1,56,Female,Designer,3.26,86,5.31,7.72,3.49,0,35,119,3.57,Moderate,Moderate
1,2,46,Female,Teacher,1.85,32,7.36,9.70,3.01,0,16,299,1.91,Low,Low
2,3,32,Female,Designer,3.04,107,4.50,6.38,5.03,0,17,21,6.05,Moderate,Moderate
3,4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92,High,High
4,5,38,Female,Teacher,3.52,56,7.57,6.69,6.71,4,92,167,5.99,Moderate,High

In [21]:
df.to_csv('cleaned_sleep_mobile_stress_dataset_15000.csv', index=False)