In [108]:
import pandas as pd

In [109]:
import matplotlib.pyplot as plt
import numpy as np

In [110]:
import sqlite3

Tables from first datasets-

Users- User ID, age, gender,
This table represents the people that took place in the study. Each line is a specific human, showing their age and gender and a created user id. The primary key is the User ID. This dataset will have a D1_ prefix on the user_id.

Behaviors- User ID, stress level, notifications per day, addiction level, addicted label, app opens per day
This table represents the level of stress and contributing notifications per user id. This will be identified by the User ID.

Hours- User ID, daily screen time, sleep hours, social media hours, gaming hours, work study hours, weekend screen time
This table represents how many hours each participant estimates that they spend in each category

['transaction_id', 'user_id', 'age', 'gender', 'daily_screen_time_hours',
       'social_media_hours', 'gaming_hours', 'work_study_hours', 'sleep_hours',
       'notifications_per_day', 'app_opens_per_day', 'weekend_screen_time',
       'stress_level', 'academic_work_impact', 'addiction_level',
       'addicted_label']

Tables from 2nd dataset-

Users- This table represents the people that took place in the study. Each line is a specific human, showing their age, gender, and occupation and created user id. The 2nd dataset will have a D2_ as a prefix for the user_id.

Wellbeing- user id, sleep quality score, stress level, caffiene intake cups, physical activity minutes, notifications received per day, mental fatigue score, stress level rank, and screen time category
This table represents the different self reported categories that have to do with behaviors and wellbeing

Hours- user id, daily screen time hours, phone usage before sleep minutes, and sleep duration hours
This table represents how many hours each participant estimates that they spend in each category.

['user_id', 'age', 'gender', 'occupation', 'daily_screen_time_hours',
       'phone_usage_before_sleep_minutes', 'sleep_duration_hours',
       'sleep_quality_score', 'stress_level', 'caffeine_intake_cups',
       'physical_activity_minutes', 'notifications_received_per_day',
       'mental_fatigue_score']

In [163]:
df1 = pd.read_csv('cleaned_smartphone_usage_and_addiction.csv')
df2 = pd.read_csv('cleaned_sleep_mobile_stress_dataset_15000.csv')

Import both cleaned datasets via the csv files created after each dataset cleanup.

In [112]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users_d1 (
            user_id TEXT PRIMARY KEY,
            age     INTEGER,
            gender  TEXT NOT NULL
        );
    """)

    connection.commit()

Open connection to Smartphone.db database and create users_d1 table.

Check from sqlite master table that users_d1 has been created and verify column names and type.

In [113]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',), ('users_d2',), ('wellbeing_d2',), ('hours_d2',)]

In [114]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(users_d1)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 0, None, 1), (1, 'age', 'INTEGER', 0, None, 0), (2, 'gender', 'TEXT', 1, None, 0)]

I originally created the first table called users, not users_d1. Dropped that table and created again.

In [115]:
#with sqlite3.connect('Smartphone.db')as connection:
    #cursor = connection.cursor()

    #cursor.execute("DROP TABLE users;")

    #connection.commit()

In [116]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',), ('users_d2',), ('wellbeing_d2',), ('hours_d2',)]

Originally this only brought back users_d1.

In [117]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(users_d1)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 0, None, 1), (1, 'age', 'INTEGER', 0, None, 0), (2, 'gender', 'TEXT', 1, None, 0)]

Open connection to Smartphone.db database and create behavior_d1 table with column names.

Check from sqlite master table that behavior_d1 has been created and verify column names and type.

In [118]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS behavior_d1 (
            user_id                     TEXT FORGEIN KEY,
            notifications_per_day       INTEGER,
            app_opens_per_day           INTEGER,
            stress_level                TEXT NOT NULL,
            addiction_level             TEXT NOT NULL,
            addicted_label              TEXT NOT NULL
        );
    """)

    connection.commit()

In [119]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',), ('users_d2',), ('wellbeing_d2',), ('hours_d2',)]

In [120]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(behavior_d1)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 1, None, 0), (1, 'notifications_per_day', 'INTEGER', 0, None, 0), (2, 'app_opens_per_day', 'INTEGER', 0, None, 0), (3, 'stress_level', 'TEXT', 1, None, 0), (4, 'addiction_level', 'TEXT', 1, None, 0), (5, 'addicted_label', 'TEXT', 1, None, 0)]

Created behavior_d1 incorrectly, drop table.

In [121]:
#with sqlite3.connect('Smartphone.db') as connection:
        #cursor = connection.cursor()

        #cursor.execute('DROP TABLE behavior_d1;')
       # connection.commit()

Originally this only showed users_d1, confirming I dropped the table I created wrong.

In [122]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',), ('users_d2',), ('wellbeing_d2',), ('hours_d2',)]

In [123]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS behavior_d1 (
            user_id                     TEXT NOT NULL,
            notifications_per_day       INTEGER,
            app_opens_per_day           INTEGER,
            stress_level                TEXT NOT NULL,
            addiction_level             TEXT NOT NULL,
            addicted_label              TEXT NOT NULL
        );
    """)

    connection.commit()

In [124]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(behavior_d1)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 1, None, 0), (1, 'notifications_per_day', 'INTEGER', 0, None, 0), (2, 'app_opens_per_day', 'INTEGER', 0, None, 0), (3, 'stress_level', 'TEXT', 1, None, 0), (4, 'addiction_level', 'TEXT', 1, None, 0), (5, 'addicted_label', 'TEXT', 1, None, 0)]

Open connection to Smartphone.db database and create hours_d1 table.

Check from sqlite master table that hours_d1 has been created and verify column names and type.

In [125]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS hours_d1 (
            user_id                     TEXT NOT NULL,
            daily_screen_time_hours     REAL,
            social_media_hours          REAL,
            gaming_hours                REAL,
            work_study_hours            REAL,
            sleep_hours                 REAL,
            weekend_screen_time         REAL
        );
    """)

    connection.commit()

In [126]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',), ('users_d2',), ('wellbeing_d2',), ('hours_d2',)]

In [127]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(hours_d1)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 1, None, 0), (1, 'daily_screen_time_hours', 'REAL', 0, None, 0), (2, 'social_media_hours', 'REAL', 0, None, 0), (3, 'gaming_hours', 'REAL', 0, None, 0), (4, 'work_study_hours', 'REAL', 0, None, 0), (5, 'sleep_hours', 'REAL', 0, None, 0), (6, 'weekend_screen_time', 'REAL', 0, None, 0)]

Open connection to Smartphone.db database and create users_d1 table.

Check from sqlite master table that users_d2 has been created and verify column names and type.

In [128]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users_d2 (
            user_id     TEXT NOT NULL,
            age         INTEGER,
            gender      TEXT NOT NULL,
            occupation  TEXT NOT NULL
        );
    """)

    connection.commit()

In [129]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',), ('users_d2',), ('wellbeing_d2',), ('hours_d2',)]

In [130]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(users_d2)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 1, None, 0), (1, 'age', 'INTEGER', 0, None, 0), (2, 'gender', 'TEXT', 1, None, 0), (3, 'occupation', 'TEXT', 1, None, 0)]

Open connection to Smartphone.db database and create wellbeing_d1 table.

Check from sqlite master table that wellbeing_d1 has been created and verify column names and type.

In [131]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS wellbeing_d2 (
            user_id                         TEXT NOT NULL,
            sleep_quality_score             REAL,
            stress_level                    REAL,
            caffeine_intake_cups            INTEGER,
            physical_activity_minutes       INTEGER,
            notifications_received_per_day  INTEGER,
            mental_fatigue_score            REAL,
            stress_level_rank               TEXT NOT NULL,
            screen_time_category            TEXT NOT NULL
        );
    """)

    connection.commit()

In [132]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',), ('users_d2',), ('wellbeing_d2',), ('hours_d2',)]

In [133]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(wellbeing_d2)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 1, None, 0), (1, 'sleep_quality_score', 'REAL', 0, None, 0), (2, 'stress_level', 'REAL', 0, None, 0), (3, 'caffeine_intake_cups', 'INTEGER', 0, None, 0), (4, 'physical_activity_minutes', 'INTEGER', 0, None, 0), (5, 'notifications_received_per_day', 'INTEGER', 0, None, 0), (6, 'mental_fatigue_score', 'REAL', 0, None, 0), (7, 'stress_level_rank', 'TEXT', 1, None, 0), (8, 'screen_time_category', 'TEXT', 1, None, 0)]

Open connection to Smartphone.db database and create hours_d2 table.

Check from sqlite master table that hours_d2 has been created and verify column names and type.

In [134]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS hours_d2 (
            user_id                             TEXT NOT NULL,
            daily_screen_time_hours             REAL,
            phone_usage_before_sleep_minutes    INTEGER,
            sleep_duration_hours                REAL
        );
    """)

    connection.commit()

In [135]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',), ('users_d2',), ('wellbeing_d2',), ('hours_d2',)]

In [136]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(wellbeing_d2)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 1, None, 0), (1, 'sleep_quality_score', 'REAL', 0, None, 0), (2, 'stress_level', 'REAL', 0, None, 0), (3, 'caffeine_intake_cups', 'INTEGER', 0, None, 0), (4, 'physical_activity_minutes', 'INTEGER', 0, None, 0), (5, 'notifications_received_per_day', 'INTEGER', 0, None, 0), (6, 'mental_fatigue_score', 'REAL', 0, None, 0), (7, 'stress_level_rank', 'TEXT', 1, None, 0), (8, 'screen_time_category', 'TEXT', 1, None, 0)]

Created the users_d1 dataframe by selecting only the necessary columns from the cleaned dataset. Run head request to verify and preview the data.

In [137]:
users_d1 = df1[
    [
        'user_id',
        'age',
        'gender'
    ]
]

In [138]:
users_d1.head()

     user_id  age gender
0  D1_U00003   31  Other
1  D1_U00004   32  Other
2  D1_U00005   25   Male
3  D1_U00006   26   Male
4  D1_U00007   25   Male

In [139]:
with sqlite3.connect('Smartphone.db') as connection:
    users_d1.to_sql(
        'users_d1',
        connection,
        if_exists='replace',
        index=False
    )

Opened a connection to the Smartphone.db SQLite database and imported the users_d1 dataframe as the users_d1 table. The if_exists='replace' option recreates the table if it alrady exists, preventing duplicate records when rerunning the notebook. Setting index=False prevents the pandas index from being added as an extra column in the database. 

Open connection and run SQL query to make sure it is functional and returns the correct number of rows.

In [140]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM users_d1')
    print(cursor.fetchone())

(6681,)

Created the behavior_d1 dataframe by selecting only the necessary columns from the cleaned dataset. Run head request to verify and preview the data.

In [141]:
behavior_d1 = df1[
    [
        'user_id',
        'notifications_per_day',
        'app_opens_per_day',
        'stress_level',
        'addiction_level',
        'addicted_label'
    ]
]

In [142]:
behavior_d1.head()

,user_id,notifications_per_day,app_opens_per_day,stress_level,addiction_level,addicted_label
0,D1_U00003,44,106,High,Mild,No
1,D1_U00004,178,107,High,Moderate,Yes
2,D1_U00005,136,177,Low,Severe,Yes
3,D1_U00006,82,56,Medium,Severe,Yes
4,D1_U00007,165,95,Medium,Severe,Yes

Opened a connection to the Smartphone.db SQLite database and imported the behavior_d1 dataframe as the behavior_d1 table. The if_exists='replace' option recreates the table if it alrady exists, preventing duplicate records when rerunning the notebook. Setting index=False prevents the pandas index from being added as an extra column in the database. 

Open connection and run SQL query to make sure it is functional and returns the correct number of rows.

In [143]:
with sqlite3.connect('Smartphone.db') as connection:
    behavior_d1.to_sql(
        'behavior_d1',
        connection,
        if_exists='replace',
        index=False
    )

In [144]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM behavior_d1')
    print(cursor.fetchone())

(6681,)

Created the hours_d1 dataframe by selecting only the necessary columns from the cleaned dataset. Run head request to verify and preview the data.

In [145]:
hours_d1 = df1[
    [
        'user_id',
        'daily_screen_time_hours',
        'social_media_hours',
        'gaming_hours',
        'work_study_hours',
        'sleep_hours',
        'weekend_screen_time'
    ]
]

In [146]:
hours_d1.head()

,user_id,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,weekend_screen_time
0,D1_U00003,6.06,1.36,3.83,2.35,4.92,8.68
1,D1_U00004,7.83,5.85,1.51,3.54,8.23,9.77
2,D1_U00005,9.96,5.92,3.42,5.27,6.21,12.55
3,D1_U00006,9.32,4.26,0.29,3.99,6.90,10.98
4,D1_U00007,10.40,4.93,1.60,0.86,8.61,11.43

Opened a connection to the Smartphone.db SQLite database and imported the hours_d1 dataframe as the hours_d1 table. The if_exists='replace' option recreates the table if it alrady exists, preventing duplicate records when rerunning the notebook. Setting index=False prevents the pandas index from being added as an extra column in the database. 

Open connection and run SQL query to make sure it is functional and returns the correct number of rows.

In [147]:
with sqlite3.connect('Smartphone.db') as connection:
    hours_d1.to_sql(
        'hours_d1',
        connection,
        if_exists='replace',
        index=False
    )

In [148]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM hours_d1')
    print(cursor.fetchone())

(6681,)

Created the users_d2 dataframe by selecting only the necessary columns from the cleaned dataset. Run head request to verify and preview the data.

In [149]:
users_d2 = df2[
    [
        'user_id',
        'age',
        'gender',
        'occupation'
    ]
]

In [150]:
users_d2.head()

  user_id  age  gender         occupation
0    D2_1   56  Female           Designer
1    D2_2   46  Female            Teacher
2    D2_3   32  Female           Designer
3    D2_4   25    Male  Software Engineer
4    D2_5   38  Female            Teacher

Opened a connection to the Smartphone.db SQLite database and imported the users_d2 dataframe as the users_d2 table. The if_exists='replace' option recreates the table if it alrady exists, preventing duplicate records when rerunning the notebook. Setting index=False prevents the pandas index from being added as an extra column in the database. 

Open connection and run SQL query to make sure it is functional and returns the correct number of rows.

In [151]:
with sqlite3.connect('Smartphone.db') as connection:
    users_d2.to_sql(
        'users_d2',
        connection,
        if_exists='replace',
        index=False
    )

In [152]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM users_d2')
    print(cursor.fetchone())

(15000,)

Created the wellbeing_d2 dataframe by selecting only the necessary columns from the cleaned dataset. Run head request to verify and preview the data.

In [153]:
wellbeing_d2 = df2[
    [
        'user_id',
        'sleep_quality_score',
        'stress_level',
        'caffeine_intake_cups',
        'physical_activity_minutes',
        'notifications_received_per_day',
        'mental_fatigue_score',
        'stress_level_rank',
        'screen_time_category'
    ]
]

In [154]:
wellbeing_d2.head()

,user_id,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score,stress_level_rank,screen_time_category
0,D2_1,7.72,3.49,0,35,119,3.57,Medium,Moderate
1,D2_2,9.70,3.01,0,16,299,1.91,Low,Low
2,D2_3,6.38,5.03,0,17,21,6.05,Medium,Moderate
3,D2_4,5.53,10.00,0,3,220,9.92,High,High
4,D2_5,6.69,6.71,4,92,167,5.99,High,Moderate

Opened a connection to the Smartphone.db SQLite database and imported the wellbeing_d2 dataframe as the wellbeing_d2 table. The if_exists='replace' option recreates the table if it alrady exists, preventing duplicate records when rerunning the notebook. Setting index=False prevents the pandas index from being added as an extra column in the database. 

Open connection and run SQL query to make sure it is functional and returns the correct number of rows.

In [155]:
with sqlite3.connect('Smartphone.db') as connection:
    wellbeing_d2.to_sql(
        'wellbeing_d2',
        connection,
        if_exists='replace',
        index=False
    )

In [156]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM wellbeing_d2')
    print(cursor.fetchone())

(15000,)

Created the hours_d2 dataframe by selecting only the necessary columns from the cleaned dataset. Run head request to verify and preview the data.

In [157]:
hours_d2 = df2[
    [
        'user_id',
        'daily_screen_time_hours',
        'phone_usage_before_sleep_minutes',
        'sleep_duration_hours'
    ]
]

In [158]:
hours_d2.head()

,user_id,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours
0,D2_1,3.26,86,5.31
1,D2_2,1.85,32,7.36
2,D2_3,3.04,107,4.50
3,D2_4,9.00,36,6.68
4,D2_5,3.52,56,7.57

Opened a connection to the Smartphone.db SQLite database and imported the hours_d2 dataframe as the hours_d2 table. The if_exists='replace' option recreates the table if it alrady exists, preventing duplicate records when rerunning the notebook. Setting index=False prevents the pandas index from being added as an extra column in the database. 

Open connection and run SQL query to make sure it is functional and returns the correct number of rows.

In [159]:
with sqlite3.connect('Smartphone.db') as connection:
    hours_d2.to_sql(
        'hours_d2',
        connection,
        if_exists='replace',
        index=False
    )

In [160]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM hours_d2')
    print(cursor.fetchone())

(15000,)

The database added duplicates when reruning entire notebook. I needed to change the 'append' option on the if exists line to replace so it does not add more if/when I rerun the notebook. Changing all to_sql calls and reruning from begining to end once I change it to replace. 

IT WORKED! There are no longer triple the number of rows.

Saved to Markdown-
Base query structure-

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        _
        _
        _;
        """)

    print(cursor.fetchall())

In [161]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT *
        FROM users_d1
        LIMIT 10;
        """)

    print(cursor.fetchall())

[('D1_U00003', 31, 'Other'), ('D1_U00004', 32, 'Other'), ('D1_U00005', 25, 'Male'), ('D1_U00006', 26, 'Male'), ('D1_U00007', 25, 'Male'), ('D1_U00008', 26, 'Male'), ('D1_U00010', 35, 'Other'), ('D1_U00011', 34, 'Female'), ('D1_U00013', 33, 'Other'), ('D1_U00015', 19, 'Male')]

The fetchall is not easily readable. Try this for a base SQL Query structure instead.

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        -
        -
        -;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

In [ ]:
#display first 10 users
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT *
        FROM users_d1
        LIMIT 10;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

('D1_U00003', 31, 'Other')
('D1_U00004', 32, 'Other')
('D1_U00005', 25, 'Male')
('D1_U00006', 26, 'Male')
('D1_U00007', 25, 'Male')
('D1_U00008', 26, 'Male')
('D1_U00010', 35, 'Other')
('D1_U00011', 34, 'Female')
('D1_U00013', 33, 'Other')
('D1_U00015', 19, 'Male')

In [ ]:
#Count users- only fetchone

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT COUNT(*) FROM users_d1;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

(6681,)

In [ ]:
#Find the min, max, and average age in d1

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT MIN(age), MAX(age), AVG(age) FROM users_d1;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

(18, 35, 26.580601706331386)

In [176]:
#Find the min, max, and average age 

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT MIN(age), MAX(age), AVG(age) FROM users_d2;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

(18, 59, 38.48846666666667)

In [168]:
#Display users from d1 from oldest to youngest

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
       SELECT * FROM users_d1 ORDER BY age DESC;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

('D1_U00010', 35, 'Other')
('D1_U00018', 35, 'Female')
('D1_U00028', 35, 'Male')
('D1_U00033', 35, 'Other')
('D1_U00057', 35, 'Male')
('D1_U00153', 35, 'Female')
('D1_U00163', 35, 'Male')
('D1_U00168', 35, 'Other')
('D1_U00169', 35, 'Male')
('D1_U00199', 35, 'Female')
('D1_U00240', 35, 'Female')
('D1_U00262', 35, 'Other')
('D1_U00309', 35, 'Male')
('D1_U00313', 35, 'Male')
('D1_U00315', 35, 'Female')
('D1_U00320', 35, 'Male')
('D1_U00356', 35, 'Female')
('D1_U00393', 35, 'Other')
('D1_U00405', 35, 'Male')
('D1_U00427', 35, 'Other')
('D1_U00452', 35, 'Female')
('D1_U00456', 35, 'Female')
('D1_U00458', 35, 'Male')
('D1_U00466', 35, 'Male')
('D1_U00476', 35, 'Other')
('D1_U00497', 35, 'Male')
('D1_U00508', 35, 'Female')
('D1_U00512', 35, 'Other')
('D1_U00559', 35, 'Male')
('D1_U00583', 35, 'Male')
('D1_U00585', 35, 'Other')
('D1_U00598', 35, 'Other')
('D1_U00605', 35, 'Other')
('D1_U00612', 35, 'Female')
('D1_U00699', 35, 'Male')
('D1_U00714', 35, 'Other')
('D1_U00724', 35, 'Female')
('D1_U00808', 35, 'Male')
('D1_U00828', 35, 'Male')
('D1_U00859', 35, 'Female')
('D1_U00860', 35, 'Male')
('D1_U00911', 35, 'Female')
('D1_U00916', 35, 'Male')
('D1_U00921', 35, 'Male')
('D1_U00931', 35, 'Other')
('D1_U00934', 35, 'Male')
('D1_U00938', 35, 'Male')
('D1_U00977', 35, 'Male')
('D1_U00989', 35, 'Female')
('D1_U00992', 35, 'Male')
('D1_U01020', 35, 'Male')
('D1_U01025', 35, 'Male')
('D1_U01047', 35, 'Female')
('D1_U01072', 35, 'Other')
('D1_U01076', 35, 'Male')
('D1_U01094', 35, 'Male')
('D1_U01119', 35, 'Other')
('D1_U01126', 35, 'Male')
('D1_U01156', 35, 'Other')
('D1_U01163', 35, 'Other')
('D1_U01168', 35, 'Female')
('D1_U01181', 35, 'Other')
('D1_U01217', 35, 'Other')
('D1_U01243', 35, 'Male')
('D1_U01257', 35, 'Male')
('D1_U01300', 35, 'Male')
('D1_U01324', 35, 'Female')
('D1_U01345', 35, 'Other')
('D1_U01347', 35, 'Female')
('D1_U01356', 35, 'Male')
('D1_U01390', 35, 'Other')
('D1_U01398', 35, 'Female')
('D1_U01409', 35, 'Female')
('D1_U01432', 35, 'Other')
('D1_U01441', 35, 'Other')
('D1_U01472', 35, 'Male')
('D1_U01495', 35, 'Other')
('D1_U01500', 35, 'Male')
('D1_U01515', 35, 'Other')
('D1_U01543', 35, 'Other')
('D1_U01555', 35, 'Other')
('D1_U01557', 35, 'Female')
('D1_U01565', 35, 'Female')
('D1_U01576', 35, 'Female')
('D1_U01581', 35, 'Female')
('D1_U01587', 35, 'Male')
('D1_U01595', 35, 'Other')
('D1_U01602', 35, 'Male')
('D1_U01667', 35, 'Male')
('D1_U01669', 35, 'Male')
('D1_U01681', 35, 'Other')
('D1_U01724', 35, 'Female')
('D1_U01755', 35, 'Other')
('D1_U01804', 35, 'Female')
('D1_U01814', 35, 'Male')
('D1_U01816', 35, 'Male')
('D1_U01822', 35, 'Male')
('D1_U01843', 35, 'Female')
('D1_U01851', 35, 'Other')
('D1_U01868', 35, 'Female')
('D1_U01882', 35, 'Female')
('D1_U01893', 35, 'Female')
('D1_U01896', 35, 'Male')
('D1_U01898', 35, 'Female')
('D1_U01923', 35, 'Other')
('D1_U01930', 35, 'Male')
('D1_U01939', 35, 'Female')
('D1_U01946', 35, 'Male')
('D1_U01955', 35, 'Male')
('D1_U02031', 35, 'Female')
('D1_U02050', 35, 'Other')
('D1_U02063', 35, 'Other')
('D1_U02067', 35, 'Other')
('D1_U02084', 35, 'Female')
('D1_U02095', 35, 'Male')
('D1_U02110', 35, 'Male')
('D1_U02114', 35, 'Other')
('D1_U02128', 35, 'Other')
('D1_U02138', 35, 'Other')
('D1_U02141', 35, 'Male')
('D1_U02162', 35, 'Other')
('D1_U02179', 35, 'Female')
('D1_U02187', 35, 'Female')
('D1_U02238', 35, 'Male')
('D1_U02244', 35, 'Female')
('D1_U02291', 35, 'Other')
('D1_U02294', 35, 'Male')
('D1_U02298', 35, 'Other')
('D1_U02323', 35, 'Female')
('D1_U02338', 35, 'Male')
('D1_U02374', 35, 'Other')
('D1_U02396', 35, 'Female')
('D1_U02423', 35, 'Male')
('D1_U02454', 35, 'Other')
('D1_U02486', 35, 'Female')
('D1_U02514', 35, 'Female')
('D1_U02554', 35, 'Female')
('D1_U02589', 35, 'Male')
('D1_U02598', 35, 'Male')
('D1_U02608', 35, 'Other')
('D1_U02696', 35, 'Female')
('D1_U02752', 35, 'Female')
('D1_U02766', 35, 'Female')
('D1_U02807', 35, 'Male')
('D1_U02820', 35, 'Female')
('D1_U02824', 35, 'Other')
('D1_U02848', 35, 'Other')
('D1_U02858', 35, 'Other')
('D1_U02871', 35, 'Female')
('D1_U02875', 35, 'Male')
('D1_U02882', 35, 'Female')
('D1_U02973', 35, 'Other')
('D1_U02982', 35, 'Female')
('D1_U03038', 35, 'Male')
('D1_U03055', 35, 'Other')
('D1_U03061', 35, 'Male')
('D1_U03073', 35, 'Other')
('D1_U03078', 35, 'Male')
('D1_U03080', 35, 'Other')
('D1_U03090', 35, 'Female')
('D1_U03096', 35, 'Other')
('D1_U03106', 35, 'Male')
('D1_U03119', 35, 'Female')
('D1_U03175', 35, 'Female')
('D1_U03184', 35, 'Other')
('D1_U03185', 35, 'Female')
('D1_U03190', 35, 'Female')
('D1_U03204', 35, 'Male')
('D1_U03210', 35, 'Female')
('D1_U03223', 35, 'Male')
('D1_U03244', 35, 'Male')
('D1_U03247', 35, 'Female')
('D1_U03265', 35, 'Male')
('D1_U03311', 35, 'Other')
('D1_U03312', 35, 'Female')
('D1_U03336', 35, 'Other')
('D1_U03386', 35, 'Female')
('D1_U03398', 35, 'Male')
('D1_U03406', 35, 'Other')
('D1_U03430', 35, 'Other')
('D1_U03454', 35, 'Other')
('D1_U03476', 35, 'Other')
('D1_U03479', 35, 'Other')
('D1_U03492', 35, 'Male')
('D1_U03507', 35, 'Male')
('D1_U03511', 35, 'Male')
('D1_U03573', 35, 'Male')
('D1_U03629', 35, 'Female')
('D1_U03639', 35, 'Other')
('D1_U03687', 35, 'Male')
('D1_U03690', 35, 'Other')
('D1_U03721', 35, 'Female')
('D1_U03740', 35, 'Male')
('D1_U03781', 35, 'Other')
('D1_U03803', 35, 'Female')
('D1_U03823', 35, 'Other')
('D1_U03848', 35, 'Other')
('D1_U03886', 35, 'Male')
('D1_U03896', 35, 'Other')
('D1_U03899', 35, 'Other')
('D1_U03962', 35, 'Other')
('D1_U03974', 35, 'Other')
('D1_U03978', 35, 'Male')
('D1_U03999', 35, 'Male')
('D1_U04028', 35, 'Male')
('D1_U04060', 35, 'Male')
('D1_U04080', 35, 'Female')
('D1_U04098', 35, 'Male')
('D1_U04101', 35, 'Female')
('D1_U04132', 35, 'Other')
('D1_U04161', 35, 'Female')
('D1_U04198', 35, 'Female')
('D1_U04233', 35, 'Female')
('D1_U04257', 35, 'Male')
('D1_U04278', 35, 'Other')
('D1_U04294', 35, 'Female')
('D1_U04333', 35, 'Other')
('D1_U04335', 35, 'Female')
('D1_U04378', 35, 'Female')
('D1_U04447', 35, 'Male')
('D1_U04470', 35, 'Female')
('D1_U04487', 35, 'Female')
('D1_U04504', 35, 'Female')
('D1_U04522', 35, 'Other')
('D1_U04546', 35, 'Other')
('D1_U04606', 35, 'Other')
('D1_U04610', 35, 'Male')
('D1_U04646', 35, 'Other')
('D1_U04659', 35, 'Male')
('D1_U04679', 35, 'Female')
('D1_U04699', 35, 'Female')
('D1_U04702', 35, 'Other')
('D1_U04711', 35, 'Other')
('D1_U04717', 35, 'Other')
('D1_U04731', 35, 'Other')
('D1_U04743', 35, 'Other')
('D1_U04747', 35, 'Male')
('D1_U04749', 35, 'Other')
('D1_U04751', 35, 'Other')
('D1_U04765', 35, 'Female')
('D1_U04793', 35, 'Female')
('D1_U04812', 35, 'Other')
('D1_U04813', 35, 'Female')
('D1_U04849', 35, 'Other')
('D1_U04862', 35, 'Male')
('D1_U04874', 35, 'Female')
('D1_U04956', 35, 'Female')
('D1_U04984', 35, 'Other')
('D1_U04991', 35, 'Male')
('D1_U05002', 35, 'Female')
('D1_U05029', 35, 'Male')
('D1_U05033', 35, 'Other')
('D1_U05043', 35, 'Male')
('D1_U05044', 35, 'Female')
('D1_U05050', 35, 'Female')
('D1_U05086', 35, 'Female')
('D1_U05097', 35, 'Female')
('D1_U05106', 35, 'Female')
('D1_U05107', 35, 'Other')
('D1_U05122', 35, 'Other')
('D1_U05125', 35, 'Other')
('D1_U05148', 35, 'Male')
('D1_U05160', 35, 'Other')
('D1_U05200', 35, 'Other')
('D1_U05211', 35, 'Other')
('D1_U05214', 35, 'Other')
('D1_U05242', 35, 'Other')
('D1_U05288', 35, 'Female')
('D1_U05292', 35, 'Male')
('D1_U05357', 35, 'Other')
('D1_U05373', 35, 'Other')
('D1_U05397', 35, 'Other')
('D1_U05398', 35, 'Other')
('D1_U05421', 35, 'Other')
('D1_U05493', 35, 'Other')
('D1_U05499', 35, 'Female')
('D1_U05502', 35, 'Male')
('D1_U05510', 35, 'Male')
('D1_U05528', 35, 'Female')
('D1_U05581', 35, 'Other')
('D1_U05582', 35, 'Other')
('D1_U05588', 35, 'Other')
('D1_U05607', 35, 'Male')
('D1_U05632', 35, 'Male')
('D1_U05656', 35, 'Male')
('D1_U05670', 35, 'Male')
('D1_U05694', 35, 'Male')
('D1_U05710', 35, 'Male')
('D1_U05727', 35, 'Female')
('D1_U05732', 35, 'Female')
('D1_U05733', 35, 'Female')
('D1_U05734', 35, 'Female')
('D1_U05764', 35, 'Other')
('D1_U05825', 35, 'Male')
('D1_U05830', 35, 'Female')
('D1_U05834', 35, 'Other')
('D1_U05893', 35, 'Male')
('D1_U05936', 35, 'Other')
('D1_U05950', 35, 'Male')
('D1_U05952', 35, 'Other')
('D1_U05978', 35, 'Female')
('D1_U06032', 35, 'Other')
('D1_U06042', 35, 'Male')
('D1_U06107', 35, 'Other')
('D1_U06130', 35, 'Male')
('D1_U06144', 35, 'Male')
('D1_U06203', 35, 'Female')
('D1_U06230', 35, 'Female')
('D1_U06234', 35, 'Male')
('D1_U06254', 35, 'Male')
('D1_U06257', 35, 'Male')
('D1_U06287', 35, 'Female')
('D1_U06320', 35, 'Female')
('D1_U06330', 35, 'Other')
('D1_U06335', 35, 'Male')
('D1_U06403', 35, 'Other')
('D1_U06430', 35, 'Male')
('D1_U06471', 35, 'Male')
('D1_U06477', 35, 'Female')
('D1_U06500', 35, 'Male')
('D1_U06510', 35, 'Female')
('D1_U06539', 35, 'Male')
('D1_U06582', 35, 'Female')
('D1_U06584', 35, 'Other')
('D1_U06586', 35, 'Male')
('D1_U06593', 35, 'Male')
('D1_U06621', 35, 'Female')
('D1_U06635', 35, 'Male')
('D1_U06643', 35, 'Female')
('D1_U06655', 35, 'Male')
('D1_U06673', 35, 'Other')
('D1_U06677', 35, 'Male')
('D1_U06744', 35, 'Female')
('D1_U06761', 35, 'Other')
('D1_U06781', 35, 'Male')
('D1_U06804', 35, 'Female')
('D1_U06915', 35, 'Male')
('D1_U06944', 35, 'Female')
('D1_U06984', 35, 'Other')
('D1_U06985', 35, 'Other')
('D1_U06991', 35, 'Male')
('D1_U07011', 35, 'Other')
('D1_U07031', 35, 'Other')
('D1_U07033', 35, 'Other')
('D1_U07040', 35, 'Male')
('D1_U07060', 35, 'Female')
('D1_U07061', 35, 'Female')
('D1_U07063', 35, 'Other')
('D1_U07078', 35, 'Other')
('D1_U07083', 35, 'Other')
('D1_U07087', 35, 'Other')
('D1_U07098', 35, 'Female')
('D1_U07123', 35, 'Female')
('D1_U07126', 35, 'Other')
('D1_U07147', 35, 'Female')
('D1_U07150', 35, 'Female')
('D1_U07156', 35, 'Other')
('D1_U07184', 35, 'Male')
('D1_U07193', 35, 'Female')
('D1_U07207', 35, 'Female')
('D1_U07219', 35, 'Male')
('D1_U07226', 35, 'Female')
('D1_U07235', 35, 'Male')
('D1_U07252', 35, 'Other')
('D1_U07259', 35, 'Other')
('D1_U07269', 35, 'Male')
('D1_U07305', 35, 'Male')
('D1_U07314', 35, 'Other')
('D1_U07332', 35, 'Other')
('D1_U07338', 35, 'Other')
('D1_U07348', 35, 'Male')
('D1_U07349', 35, 'Other')
('D1_U07361', 35, 'Female')
('D1_U07377', 35, 'Other')
('D1_U07429', 35, 'Other')
('D1_U07468', 35, 'Male')
('D1_U07472', 35, 'Male')
('D1_U00011', 34, 'Female')
('D1_U00024', 34, 'Female')
('D1_U00031', 34, 'Other')
('D1_U00056', 34, 'Male')
('D1_U00070', 34, 'Other')
('D1_U00093', 34, 'Male')
('D1_U00114', 34, 'Male')
('D1_U00137', 34, 'Other')
('D1_U00143', 34, 'Male')
('D1_U00146', 34, 'Other')
('D1_U00155', 34, 'Other')
('D1_U00165', 34, 'Female')
('D1_U00171', 34, 'Female')
('D1_U00232', 34, 'Female')
('D1_U00282', 34, 'Male')
('D1_U00298', 34, 'Other')
('D1_U00331', 34, 'Female')
('D1_U00366', 34, 'Other')
('D1_U00368', 34, 'Male')
('D1_U00396', 34, 'Female')
('D1_U00408', 34, 'Female')
('D1_U00412', 34, 'Female')
('D1_U00420', 34, 'Female')
('D1_U00429', 34, 'Male')
('D1_U00457', 34, 'Female')
('D1_U00490', 34, 'Female')
('D1_U00500', 34, 'Male')
('D1_U00519', 34, 'Female')
('D1_U00525', 34, 'Other')
('D1_U00531', 34, 'Female')
('D1_U00540', 34, 'Female')
('D1_U00542', 34, 'Female')
('D1_U00549', 34, 'Female')
('D1_U00602', 34, 'Female')
('D1_U00647', 34, 'Female')
('D1_U00698', 34, 'Other')
('D1_U00726', 34, 'Female')
('D1_U00728', 34, 'Other')
('D1_U00730', 34, 'Female')
('D1_U00732', 34, 'Male')
('D1_U00741', 34, 'Female')
('D1_U00756', 34, 'Male')
('D1_U00770', 34, 'Other')
('D1_U00832', 34, 'Female')
('D1_U00885', 34, 'Male')
('D1_U00886', 34, 'Female')
('D1_U00904', 34, 'Female')
('D1_U00928', 34, 'Female')
('D1_U00929', 34, 'Other')
('D1_U00937', 34, 'Female')
('D1_U00963', 34, 'Other')
('D1_U01022', 34, 'Male')
('D1_U01049', 34, 'Other')
('D1_U01121', 34, 'Other')
('D1_U01157', 34, 'Male')
('D1_U01161', 34, 'Female')
('D1_U01165', 34, 'Other')
('D1_U01185', 34, 'Female')
('D1_U01186', 34, 'Female')
('D1_U01205', 34, 'Female')
('D1_U01224', 34, 'Other')
('D1_U01265', 34, 'Female')
('D1_U01269', 34, 'Other')
('D1_U01275', 34, 'Female')
('D1_U01284', 34, 'Male')
('D1_U01289', 34, 'Female')
('D1_U01343', 34, 'Other')
('D1_U01384', 34, 'Female')
('D1_U01389', 34, 'Male')
('D1_U01434', 34, 'Male')
('D1_U01461', 34, 'Other')
('D1_U01492', 34, 'Female')
('D1_U01517', 34, 'Other')
('D1_U01522', 34, 'Other')
('D1_U01535', 34, 'Male')
('D1_U01651', 34, 'Male')
('D1_U01692', 34, 'Other')
('D1_U01701', 34, 'Male')
('D1_U01726', 34, 'Male')
('D1_U01765', 34, 'Male')
('D1_U01784', 34, 'Other')
('D1_U01797', 34, 'Other')
('D1_U01811', 34, 'Male')
('D1_U01815', 34, 'Male')
('D1_U01883', 34, 'Other')
('D1_U01885', 34, 'Female')
('D1_U01900', 34, 'Female')
('D1_U01907', 34, 'Male')
('D1_U01926', 34, 'Female')
('D1_U01936', 34, 'Male')
('D1_U01957', 34, 'Female')
('D1_U01979', 34, 'Other')
('D1_U01996', 34, 'Male')
('D1_U02005', 34, 'Female')
('D1_U02009', 34, 'Female')
('D1_U02022', 34, 'Male')
('D1_U02026', 34, 'Male')
('D1_U02057', 34, 'Female')
('D1_U02096', 34, 'Male')
('D1_U02104', 34, 'Female')
('D1_U02117', 34, 'Female')
('D1_U02137', 34, 'Male')
('D1_U02143', 34, 'Other')
('D1_U02158', 34, 'Female')
('D1_U02189', 34, 'Other')
('D1_U02194', 34, 'Other')
('D1_U02309', 34, 'Female')
('D1_U02322', 34, 'Other')
('D1_U02384', 34, 'Female')
('D1_U02385', 34, 'Female')
('D1_U02398', 34, 'Other')
('D1_U02414', 34, 'Female')
('D1_U02438', 34, 'Female')
('D1_U02450', 34, 'Other')
('D1_U02460', 34, 'Female')
('D1_U02463', 34, 'Other')
('D1_U02471', 34, 'Male')
('D1_U02475', 34, 'Female')
('D1_U02481', 34, 'Other')
('D1_U02485', 34, 'Female')
('D1_U02507', 34, 'Male')
('D1_U02519', 34, 'Other')
('D1_U02537', 34, 'Other')
('D1_U02572', 34, 'Female')
('D1_U02599', 34, 'Male')
('D1_U02609', 34, 'Female')
('D1_U02610', 34, 'Female')
('D1_U02621', 34, 'Female')
('D1_U02629', 34, 'Male')
('D1_U02643', 34, 'Female')
('D1_U02644', 34, 'Female')
('D1_U02648', 34, 'Female')
('D1_U02652', 34, 'Other')
('D1_U02673', 34, 'Male')
('D1_U02680', 34, 'Other')
('D1_U02693', 34, 'Female')
('D1_U02694', 34, 'Male')
('D1_U02709', 34, 'Other')
('D1_U02728', 34, 'Other')
('D1_U02737', 34, 'Male')
('D1_U02765', 34, 'Other')
('D1_U02795', 34, 'Female')
('D1_U02862', 34, 'Female')
('D1_U02863', 34, 'Other')
('D1_U02880', 34, 'Male')
('D1_U02911', 34, 'Male')
('D1_U02956', 34, 'Male')
('D1_U02984', 34, 'Other')
('D1_U02998', 34, 'Other')
('D1_U03018', 34, 'Female')
('D1_U03025', 34, 'Male')
('D1_U03035', 34, 'Other')
('D1_U03058', 34, 'Other')
('D1_U03072', 34, 'Female')
('D1_U03131', 34, 'Male')
('D1_U03152', 34, 'Other')
('D1_U03165', 34, 'Female')
('D1_U03167', 34, 'Male')
('D1_U03171', 34, 'Male')
('D1_U03176', 34, 'Female')
('D1_U03191', 34, 'Female')
('D1_U03198', 34, 'Other')
('D1_U03219', 34, 'Other')
('D1_U03229', 34, 'Female')
('D1_U03290', 34, 'Other')
('D1_U03301', 34, 'Other')
('D1_U03330', 34, 'Female')
('D1_U03365', 34, 'Other')
('D1_U03369', 34, 'Male')
('D1_U03408', 34, 'Other')
('D1_U03436', 34, 'Male')
('D1_U03442', 34, 'Other')
('D1_U03468', 34, 'Male')
('D1_U03477', 34, 'Female')
('D1_U03504', 34, 'Female')
('D1_U03506', 34, 'Male')
('D1_U03547', 34, 'Female')
('D1_U03552', 34, 'Other')
('D1_U03577', 34, 'Other')
('D1_U03590', 34, 'Female')
('D1_U03599', 34, 'Other')
('D1_U03609', 34, 'Male')
('D1_U03627', 34, 'Other')
('D1_U03635', 34, 'Other')
('D1_U03638', 34, 'Female')
('D1_U03648', 34, 'Female')
('D1_U03655', 34, 'Other')
('D1_U03720', 34, 'Other')
('D1_U03739', 34, 'Female')
('D1_U03745', 34, 'Male')
('D1_U03767', 34, 'Other')
('D1_U03783', 34, 'Other')
('D1_U03787', 34, 'Male')
('D1_U03800', 34, 'Other')
('D1_U03805', 34, 'Female')
('D1_U03812', 34, 'Other')
('D1_U03817', 34, 'Female')
('D1_U03833', 34, 'Female')
('D1_U03851', 34, 'Male')
('D1_U03859', 34, 'Other')
('D1_U03880', 34, 'Other')
('D1_U03897', 34, 'Male')
('D1_U03910', 34, 'Male')
('D1_U03915', 34, 'Male')
('D1_U03943', 34, 'Other')
('D1_U03953', 34, 'Male')
('D1_U03977', 34, 'Male')
('D1_U03981', 34, 'Other')
('D1_U04065', 34, 'Male')
('D1_U04096', 34, 'Other')
('D1_U04107', 34, 'Female')
('D1_U04130', 34, 'Other')
('D1_U04157', 34, 'Other')
('D1_U04160', 34, 'Male')
('D1_U04168', 34, 'Male')
('D1_U04174', 34, 'Female')
('D1_U04175', 34, 'Female')
('D1_U04196', 34, 'Male')
('D1_U04211', 34, 'Other')
('D1_U04227', 34, 'Female')
('D1_U04235', 34, 'Male')
('D1_U04285', 34, 'Male')
('D1_U04369', 34, 'Other')
('D1_U04381', 34, 'Other')
('D1_U04394', 34, 'Female')
('D1_U04405', 34, 'Other')
('D1_U04452', 34, 'Other')
('D1_U04462', 34, 'Female')
('D1_U04471', 34, 'Other')
('D1_U04530', 34, 'Other')
('D1_U04580', 34, 'Other')
('D1_U04608', 34, 'Male')
('D1_U04638', 34, 'Female')
('D1_U04690', 34, 'Male')
('D1_U04710', 34, 'Other')
('D1_U04740', 34, 'Other')
('D1_U04769', 34, 'Other')
('D1_U04772', 34, 'Other')
('D1_U04805', 34, 'Male')
('D1_U04815', 34, 'Male')
('D1_U04895', 34, 'Other')
('D1_U04932', 34, 'Other')
('D1_U04936', 34, 'Female')
('D1_U05003', 34, 'Male')
('D1_U05010', 34, 'Other')
('D1_U05042', 34, 'Female')
('D1_U05047', 34, 'Male')
('D1_U05056', 34, 'Female')
('D1_U05081', 34, 'Male')
('D1_U05101', 34, 'Male')
('D1_U05110', 34, 'Other')
('D1_U05124', 34, 'Other')
('D1_U05140', 34, 'Other')
('D1_U05141', 34, 'Female')
('D1_U05142', 34, 'Female')
('D1_U05143', 34, 'Other')
('D1_U05157', 34, 'Female')
('D1_U05185', 34, 'Other')
('D1_U05218', 34, 'Male')
('D1_U05233', 34, 'Female')
('D1_U05234', 34, 'Other')
('D1_U05235', 34, 'Other')
('D1_U05239', 34, 'Female')
('D1_U05241', 34, 'Male')
('D1_U05255', 34, 'Male')
('D1_U05257', 34, 'Other')
('D1_U05272', 34, 'Female')
('D1_U05273', 34, 'Male')
('D1_U05301', 34, 'Male')
('D1_U05322', 34, 'Other')
('D1_U05374', 34, 'Male')
('D1_U05392', 34, 'Male')
('D1_U05428', 34, 'Male')
('D1_U05447', 34, 'Female')
('D1_U05463', 34, 'Other')
('D1_U05479', 34, 'Male')
('D1_U05546', 34, 'Female')
('D1_U05548', 34, 'Female')
('D1_U05580', 34, 'Other')
('D1_U05594', 34, 'Other')
('D1_U05611', 34, 'Female')
('D1_U05618', 34, 'Other')
('D1_U05636', 34, 'Female')
('D1_U05657', 34, 'Other')
('D1_U05683', 34, 'Other')
('D1_U05688', 34, 'Other')
('D1_U05723', 34, 'Other')
('D1_U05756', 34, 'Other')
('D1_U05758', 34, 'Female')
('D1_U05775', 34, 'Male')
('D1_U05856', 34, 'Male')
('D1_U05860', 34, 'Other')
('D1_U05872', 34, 'Female')
('D1_U05876', 34, 'Male')
('D1_U05899', 34, 'Female')
('D1_U06020', 34, 'Male')
('D1_U06055', 34, 'Female')
('D1_U06080', 34, 'Other')
('D1_U06103', 34, 'Female')
('D1_U06111', 34, 'Male')
('D1_U06125', 34, 'Male')
('D1_U06136', 34, 'Other')
('D1_U06147', 34, 'Other')
('D1_U06166', 34, 'Female')
('D1_U06177', 34, 'Other')
('D1_U06185', 34, 'Other')
('D1_U06199', 34, 'Other')
('D1_U06219', 34, 'Female')
('D1_U06223', 34, 'Other')
('D1_U06232', 34, 'Other')
('D1_U06267', 34, 'Other')
('D1_U06337', 34, 'Female')
('D1_U06340', 34, 'Female')
('D1_U06348', 34, 'Other')
('D1_U06354', 34, 'Male')
('D1_U06368', 34, 'Male')
('D1_U06391', 34, 'Male')
('D1_U06418', 34, 'Female')
('D1_U06426', 34, 'Other')
('D1_U06462', 34, 'Female')
('D1_U06545', 34, 'Other')
('D1_U06557', 34, 'Female')
('D1_U06565', 34, 'Other')
('D1_U06579', 34, 'Other')
('D1_U06599', 34, 'Female')
('D1_U06663', 34, 'Male')
('D1_U06695', 34, 'Female')
('D1_U06696', 34, 'Other')
('D1_U06743', 34, 'Female')
('D1_U06773', 34, 'Male')
('D1_U06788', 34, 'Female')
('D1_U06793', 34, 'Other')
('D1_U06800', 34, 'Other')
('D1_U06802', 34, 'Male')
('D1_U06813', 34, 'Female')
('D1_U06858', 34, 'Other')
('D1_U06880', 34, 'Other')
('D1_U06903', 34, 'Other')
('D1_U06904', 34, 'Female')
('D1_U06910', 34, 'Male')
('D1_U06936', 34, 'Male')
('D1_U06958', 34, 'Male')
('D1_U06987', 34, 'Female')
('D1_U07014', 34, 'Female')
('D1_U07023', 34, 'Female')
('D1_U07049', 34, 'Male')
('D1_U07052', 34, 'Female')
('D1_U07058', 34, 'Other')
('D1_U07071', 34, 'Other')
('D1_U07074', 34, 'Male')
('D1_U07076', 34, 'Other')
('D1_U07077', 34, 'Male')
('D1_U07081', 34, 'Male')
('D1_U07085', 34, 'Male')
('D1_U07188', 34, 'Other')
('D1_U07224', 34, 'Other')
('D1_U07243', 34, 'Female')
('D1_U07281', 34, 'Female')
('D1_U07291', 34, 'Male')
('D1_U07317', 34, 'Other')
('D1_U07325', 34, 'Other')
('D1_U07355', 34, 'Female')
('D1_U07385', 34, 'Female')

In [169]:
#Display users from d2 from oldest to youngest

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT * FROM users_d2 ORDER BY age DESC;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

('D2_28', 59, 'Female', 'Student')
('D2_57', 59, 'Female', 'Doctor')
('D2_96', 59, 'Female', 'Manager')
('D2_129', 59, 'Female', 'Manager')
('D2_148', 59, 'Other', 'Software Engineer')
('D2_171', 59, 'Male', 'Freelancer')
('D2_237', 59, 'Male', 'Designer')
('D2_326', 59, 'Female', 'Manager')
('D2_336', 59, 'Male', 'Freelancer')
('D2_345', 59, 'Female', 'Researcher')
('D2_370', 59, 'Male', 'Freelancer')
('D2_386', 59, 'Female', 'Researcher')
('D2_536', 59, 'Female', 'Doctor')
('D2_554', 59, 'Other', 'Teacher')
('D2_730', 59, 'Female', 'Researcher')
('D2_768', 59, 'Male', 'Freelancer')
('D2_834', 59, 'Female', 'Teacher')
('D2_944', 59, 'Female', 'Software Engineer')
('D2_971', 59, 'Male', 'Designer')
('D2_1035', 59, 'Male', 'Student')
('D2_1171', 59, 'Female', 'Software Engineer')
('D2_1211', 59, 'Female', 'Doctor')
('D2_1222', 59, 'Female', 'Student')
('D2_1272', 59, 'Female', 'Manager')
('D2_1330', 59, 'Female', 'Teacher')
('D2_1353', 59, 'Female', 'Researcher')
('D2_1356', 59, 'Male', 'Teacher')
('D2_1417', 59, 'Female', 'Doctor')
('D2_1443', 59, 'Male', 'Doctor')
('D2_1485', 59, 'Male', 'Software Engineer')
('D2_1493', 59, 'Male', 'Software Engineer')
('D2_1685', 59, 'Male', 'Manager')
('D2_1712', 59, 'Male', 'Freelancer')
('D2_1764', 59, 'Male', 'Teacher')
('D2_1778', 59, 'Male', 'Doctor')
('D2_1848', 59, 'Female', 'Teacher')
('D2_1861', 59, 'Male', 'Doctor')
('D2_1989', 59, 'Female', 'Student')
('D2_2007', 59, 'Female', 'Software Engineer')
('D2_2008', 59, 'Male', 'Software Engineer')
('D2_2014', 59, 'Female', 'Designer')
('D2_2026', 59, 'Male', 'Manager')
('D2_2070', 59, 'Male', 'Manager')
('D2_2080', 59, 'Female', 'Researcher')
('D2_2126', 59, 'Female', 'Designer')
('D2_2182', 59, 'Female', 'Teacher')
('D2_2184', 59, 'Female', 'Teacher')
('D2_2190', 59, 'Female', 'Manager')
('D2_2327', 59, 'Male', 'Doctor')
('D2_2329', 59, 'Female', 'Freelancer')
('D2_2479', 59, 'Male', 'Manager')
('D2_2490', 59, 'Female', 'Freelancer')
('D2_2504', 59, 'Female', 'Freelancer')
('D2_2589', 59, 'Male', 'Manager')
('D2_2619', 59, 'Female', 'Teacher')
('D2_2631', 59, 'Male', 'Student')
('D2_2654', 59, 'Female', 'Designer')
('D2_2673', 59, 'Female', 'Student')
('D2_2731', 59, 'Other', 'Designer')
('D2_2754', 59, 'Female', 'Software Engineer')
('D2_2897', 59, 'Female', 'Software Engineer')
('D2_2997', 59, 'Female', 'Manager')
('D2_3013', 59, 'Male', 'Software Engineer')
('D2_3165', 59, 'Other', 'Doctor')
('D2_3169', 59, 'Female', 'Doctor')
('D2_3172', 59, 'Male', 'Software Engineer')
('D2_3194', 59, 'Female', 'Student')
('D2_3283', 59, 'Female', 'Doctor')
('D2_3342', 59, 'Male', 'Student')
('D2_3459', 59, 'Male', 'Software Engineer')
('D2_3539', 59, 'Female', 'Manager')
('D2_3596', 59, 'Female', 'Teacher')
('D2_3674', 59, 'Female', 'Software Engineer')
('D2_3695', 59, 'Male', 'Researcher')
('D2_3698', 59, 'Male', 'Doctor')
('D2_3769', 59, 'Male', 'Freelancer')
('D2_3793', 59, 'Other', 'Student')
('D2_3836', 59, 'Male', 'Doctor')
('D2_4054', 59, 'Male', 'Researcher')
('D2_4076', 59, 'Male', 'Doctor')
('D2_4105', 59, 'Female', 'Designer')
('D2_4160', 59, 'Male', 'Doctor')
('D2_4170', 59, 'Female', 'Designer')
('D2_4171', 59, 'Other', 'Doctor')
('D2_4183', 59, 'Female', 'Manager')
('D2_4212', 59, 'Male', 'Manager')
('D2_4218', 59, 'Male', 'Designer')
('D2_4235', 59, 'Male', 'Researcher')
('D2_4303', 59, 'Male', 'Freelancer')
('D2_4348', 59, 'Female', 'Doctor')
('D2_4351', 59, 'Female', 'Doctor')
('D2_4353', 59, 'Female', 'Freelancer')
('D2_4485', 59, 'Male', 'Designer')
('D2_4561', 59, 'Female', 'Researcher')
('D2_4572', 59, 'Male', 'Researcher')
('D2_4632', 59, 'Male', 'Designer')
('D2_4633', 59, 'Female', 'Student')
('D2_4644', 59, 'Female', 'Freelancer')
('D2_4721', 59, 'Male', 'Teacher')
('D2_4786', 59, 'Female', 'Manager')
('D2_4835', 59, 'Female', 'Designer')
('D2_4856', 59, 'Female', 'Software Engineer')
('D2_4950', 59, 'Male', 'Researcher')
('D2_4951', 59, 'Male', 'Software Engineer')
('D2_5041', 59, 'Male', 'Manager')
('D2_5061', 59, 'Male', 'Freelancer')
('D2_5072', 59, 'Female', 'Software Engineer')
('D2_5092', 59, 'Female', 'Teacher')
('D2_5114', 59, 'Male', 'Freelancer')
('D2_5132', 59, 'Male', 'Teacher')
('D2_5141', 59, 'Female', 'Freelancer')
('D2_5182', 59, 'Female', 'Software Engineer')
('D2_5228', 59, 'Female', 'Designer')
('D2_5230', 59, 'Female', 'Student')
('D2_5235', 59, 'Female', 'Manager')
('D2_5271', 59, 'Male', 'Software Engineer')
('D2_5274', 59, 'Male', 'Designer')
('D2_5285', 59, 'Female', 'Freelancer')
('D2_5297', 59, 'Male', 'Teacher')
('D2_5302', 59, 'Female', 'Student')
('D2_5466', 59, 'Female', 'Designer')
('D2_5482', 59, 'Female', 'Researcher')
('D2_5490', 59, 'Female', 'Freelancer')
('D2_5539', 59, 'Male', 'Software Engineer')
('D2_5543', 59, 'Male', 'Software Engineer')
('D2_5614', 59, 'Male', 'Doctor')
('D2_5648', 59, 'Female', 'Designer')
('D2_5664', 59, 'Male', 'Doctor')
('D2_5818', 59, 'Female', 'Software Engineer')
('D2_5871', 59, 'Male', 'Student')
('D2_5887', 59, 'Female', 'Student')
('D2_5914', 59, 'Female', 'Teacher')
('D2_5925', 59, 'Male', 'Researcher')
('D2_5955', 59, 'Male', 'Designer')
('D2_5988', 59, 'Female', 'Software Engineer')
('D2_6041', 59, 'Male', 'Researcher')
('D2_6127', 59, 'Female', 'Researcher')
('D2_6151', 59, 'Female', 'Teacher')
('D2_6158', 59, 'Male', 'Student')
('D2_6165', 59, 'Other', 'Designer')
('D2_6176', 59, 'Female', 'Freelancer')
('D2_6189', 59, 'Female', 'Freelancer')
('D2_6209', 59, 'Female', 'Freelancer')
('D2_6326', 59, 'Female', 'Doctor')
('D2_6375', 59, 'Female', 'Designer')
('D2_6406', 59, 'Female', 'Researcher')
('D2_6463', 59, 'Male', 'Teacher')
('D2_6518', 59, 'Male', 'Manager')
('D2_6537', 59, 'Male', 'Doctor')
('D2_6540', 59, 'Male', 'Researcher')
('D2_6567', 59, 'Female', 'Doctor')
('D2_6602', 59, 'Female', 'Manager')
('D2_6605', 59, 'Female', 'Designer')
('D2_6607', 59, 'Female', 'Researcher')
('D2_6643', 59, 'Female', 'Manager')
('D2_6696', 59, 'Other', 'Designer')
('D2_6725', 59, 'Male', 'Teacher')
('D2_6742', 59, 'Female', 'Teacher')
('D2_6745', 59, 'Female', 'Researcher')
('D2_6786', 59, 'Male', 'Designer')
('D2_6791', 59, 'Female', 'Manager')
('D2_6800', 59, 'Female', 'Doctor')
('D2_6864', 59, 'Female', 'Researcher')
('D2_6919', 59, 'Female', 'Teacher')
('D2_6940', 59, 'Female', 'Freelancer')
('D2_6941', 59, 'Female', 'Student')
('D2_6973', 59, 'Male', 'Software Engineer')
('D2_7049', 59, 'Female', 'Manager')
('D2_7051', 59, 'Male', 'Manager')
('D2_7156', 59, 'Male', 'Freelancer')
('D2_7200', 59, 'Male', 'Teacher')
('D2_7224', 59, 'Female', 'Researcher')
('D2_7355', 59, 'Male', 'Researcher')
('D2_7357', 59, 'Male', 'Designer')
('D2_7368', 59, 'Female', 'Doctor')
('D2_7425', 59, 'Male', 'Software Engineer')
('D2_7503', 59, 'Male', 'Teacher')
('D2_7508', 59, 'Male', 'Designer')
('D2_7520', 59, 'Female', 'Student')
('D2_7531', 59, 'Male', 'Designer')
('D2_7533', 59, 'Male', 'Teacher')
('D2_7550', 59, 'Female', 'Doctor')
('D2_7579', 59, 'Female', 'Freelancer')
('D2_7593', 59, 'Male', 'Doctor')
('D2_7627', 59, 'Male', 'Teacher')
('D2_7644', 59, 'Female', 'Software Engineer')
('D2_7669', 59, 'Male', 'Researcher')
('D2_7707', 59, 'Female', 'Researcher')
('D2_7741', 59, 'Female', 'Student')
('D2_7769', 59, 'Female', 'Researcher')
('D2_7851', 59, 'Female', 'Designer')
('D2_7963', 59, 'Male', 'Teacher')
('D2_7981', 59, 'Female', 'Freelancer')
('D2_8103', 59, 'Male', 'Freelancer')
('D2_8106', 59, 'Male', 'Student')
('D2_8114', 59, 'Female', 'Designer')
('D2_8137', 59, 'Female', 'Freelancer')
('D2_8146', 59, 'Male', 'Teacher')
('D2_8157', 59, 'Male', 'Manager')
('D2_8162', 59, 'Male', 'Designer')
('D2_8216', 59, 'Male', 'Doctor')
('D2_8296', 59, 'Male', 'Doctor')
('D2_8319', 59, 'Female', 'Teacher')
('D2_8351', 59, 'Female', 'Teacher')
('D2_8356', 59, 'Male', 'Software Engineer')
('D2_8376', 59, 'Male', 'Doctor')
('D2_8470', 59, 'Male', 'Software Engineer')
('D2_8488', 59, 'Male', 'Researcher')
('D2_8654', 59, 'Male', 'Researcher')
('D2_8661', 59, 'Female', 'Teacher')
('D2_8702', 59, 'Male', 'Doctor')
('D2_8746', 59, 'Female', 'Teacher')
('D2_8751', 59, 'Male', 'Researcher')
('D2_8754', 59, 'Female', 'Researcher')
('D2_8758', 59, 'Female', 'Teacher')
('D2_8762', 59, 'Female', 'Designer')
('D2_8784', 59, 'Male', 'Teacher')
('D2_8826', 59, 'Male', 'Doctor')
('D2_8867', 59, 'Female', 'Designer')
('D2_8872', 59, 'Male', 'Freelancer')
('D2_8906', 59, 'Male', 'Software Engineer')
('D2_8945', 59, 'Female', 'Teacher')
('D2_8968', 59, 'Female', 'Researcher')
('D2_8992', 59, 'Female', 'Doctor')
('D2_9044', 59, 'Male', 'Freelancer')
('D2_9089', 59, 'Male', 'Software Engineer')
('D2_9138', 59, 'Male', 'Researcher')
('D2_9275', 59, 'Female', 'Researcher')
('D2_9333', 59, 'Female', 'Teacher')
('D2_9354', 59, 'Male', 'Designer')
('D2_9410', 59, 'Female', 'Freelancer')
('D2_9476', 59, 'Female', 'Software Engineer')
('D2_9535', 59, 'Female', 'Designer')
('D2_9564', 59, 'Male', 'Designer')
('D2_9565', 59, 'Male', 'Student')
('D2_9580', 59, 'Male', 'Researcher')
('D2_9659', 59, 'Female', 'Doctor')
('D2_9661', 59, 'Female', 'Freelancer')
('D2_9727', 59, 'Female', 'Doctor')
('D2_9844', 59, 'Male', 'Freelancer')
('D2_9847', 59, 'Male', 'Doctor')
('D2_9852', 59, 'Female', 'Freelancer')
('D2_9875', 59, 'Male', 'Teacher')
('D2_9884', 59, 'Male', 'Manager')
('D2_9886', 59, 'Female', 'Researcher')
('D2_10169', 59, 'Male', 'Designer')
('D2_10179', 59, 'Female', 'Doctor')
('D2_10224', 59, 'Female', 'Student')
('D2_10238', 59, 'Male', 'Freelancer')
('D2_10266', 59, 'Male', 'Freelancer')
('D2_10297', 59, 'Male', 'Teacher')
('D2_10305', 59, 'Female', 'Software Engineer')
('D2_10311', 59, 'Female', 'Doctor')
('D2_10359', 59, 'Female', 'Freelancer')
('D2_10460', 59, 'Male', 'Manager')
('D2_10496', 59, 'Female', 'Software Engineer')
('D2_10519', 59, 'Other', 'Researcher')
('D2_10536', 59, 'Male', 'Software Engineer')
('D2_10599', 59, 'Other', 'Teacher')
('D2_10640', 59, 'Male', 'Researcher')
('D2_10679', 59, 'Male', 'Software Engineer')
('D2_10680', 59, 'Male', 'Student')
('D2_10772', 59, 'Male', 'Designer')
('D2_10781', 59, 'Male', 'Designer')
('D2_10856', 59, 'Male', 'Manager')
('D2_10873', 59, 'Male', 'Designer')
('D2_10886', 59, 'Female', 'Freelancer')
('D2_10914', 59, 'Male', 'Designer')
('D2_10969', 59, 'Female', 'Researcher')
('D2_11001', 59, 'Female', 'Freelancer')
('D2_11054', 59, 'Female', 'Designer')
('D2_11141', 59, 'Male', 'Researcher')
('D2_11157', 59, 'Male', 'Teacher')
('D2_11172', 59, 'Male', 'Researcher')
('D2_11200', 59, 'Female', 'Student')
('D2_11203', 59, 'Female', 'Doctor')
('D2_11211', 59, 'Male', 'Student')
('D2_11298', 59, 'Other', 'Manager')
('D2_11381', 59, 'Male', 'Freelancer')
('D2_11416', 59, 'Male', 'Doctor')
('D2_11502', 59, 'Male', 'Freelancer')
('D2_11509', 59, 'Male', 'Student')
('D2_11588', 59, 'Female', 'Teacher')
('D2_11625', 59, 'Other', 'Software Engineer')
('D2_11630', 59, 'Male', 'Doctor')
('D2_11672', 59, 'Female', 'Teacher')
('D2_11728', 59, 'Male', 'Student')
('D2_11731', 59, 'Male', 'Freelancer')
('D2_11815', 59, 'Male', 'Manager')
('D2_11827', 59, 'Female', 'Designer')
('D2_11916', 59, 'Male', 'Student')
('D2_11961', 59, 'Female', 'Freelancer')
('D2_11975', 59, 'Female', 'Freelancer')
('D2_11977', 59, 'Male', 'Software Engineer')
('D2_11982', 59, 'Female', 'Teacher')
('D2_11997', 59, 'Male', 'Doctor')
('D2_12066', 59, 'Female', 'Designer')
('D2_12080', 59, 'Female', 'Manager')
('D2_12087', 59, 'Female', 'Student')
('D2_12159', 59, 'Female', 'Manager')
('D2_12196', 59, 'Female', 'Teacher')
('D2_12248', 59, 'Female', 'Designer')
('D2_12261', 59, 'Female', 'Software Engineer')
('D2_12266', 59, 'Male', 'Researcher')
('D2_12302', 59, 'Male', 'Researcher')
('D2_12319', 59, 'Male', 'Software Engineer')
('D2_12376', 59, 'Male', 'Student')
('D2_12452', 59, 'Female', 'Doctor')
('D2_12486', 59, 'Female', 'Freelancer')
('D2_12499', 59, 'Male', 'Software Engineer')
('D2_12502', 59, 'Female', 'Student')
('D2_12528', 59, 'Female', 'Researcher')
('D2_12610', 59, 'Female', 'Doctor')
('D2_12637', 59, 'Male', 'Designer')
('D2_12651', 59, 'Male', 'Freelancer')
('D2_12757', 59, 'Male', 'Researcher')
('D2_12840', 59, 'Male', 'Researcher')
('D2_12849', 59, 'Male', 'Student')
('D2_12858', 59, 'Male', 'Doctor')
('D2_12877', 59, 'Female', 'Teacher')
('D2_12888', 59, 'Female', 'Manager')
('D2_13032', 59, 'Male', 'Researcher')
('D2_13083', 59, 'Male', 'Freelancer')
('D2_13196', 59, 'Female', 'Software Engineer')
('D2_13353', 59, 'Female', 'Teacher')
('D2_13378', 59, 'Male', 'Student')
('D2_13401', 59, 'Male', 'Designer')
('D2_13420', 59, 'Male', 'Researcher')
('D2_13445', 59, 'Male', 'Manager')
('D2_13454', 59, 'Male', 'Designer')
('D2_13738', 59, 'Male', 'Manager')
('D2_13740', 59, 'Female', 'Teacher')
('D2_13744', 59, 'Male', 'Software Engineer')
('D2_13863', 59, 'Male', 'Freelancer')
('D2_13883', 59, 'Male', 'Teacher')
('D2_13952', 59, 'Female', 'Software Engineer')
('D2_13998', 59, 'Male', 'Designer')
('D2_14040', 59, 'Male', 'Researcher')
('D2_14068', 59, 'Female', 'Doctor')
('D2_14079', 59, 'Male', 'Student')
('D2_14116', 59, 'Female', 'Manager')
('D2_14126', 59, 'Female', 'Freelancer')
('D2_14138', 59, 'Other', 'Researcher')
('D2_14170', 59, 'Male', 'Researcher')
('D2_14282', 59, 'Male', 'Doctor')
('D2_14314', 59, 'Male', 'Designer')
('D2_14330', 59, 'Female', 'Teacher')
('D2_14333', 59, 'Male', 'Doctor')
('D2_14358', 59, 'Male', 'Teacher')
('D2_14417', 59, 'Female', 'Freelancer')
('D2_14467', 59, 'Male', 'Teacher')
('D2_14594', 59, 'Female', 'Researcher')
('D2_14648', 59, 'Female', 'Researcher')
('D2_14649', 59, 'Male', 'Student')
('D2_14810', 59, 'Male', 'Researcher')
('D2_14821', 59, 'Female', 'Teacher')
('D2_14873', 59, 'Male', 'Researcher')
('D2_14885', 59, 'Female', 'Designer')
('D2_14901', 59, 'Female', 'Doctor')
('D2_78', 58, 'Female', 'Software Engineer')
('D2_98', 58, 'Male', 'Manager')
('D2_162', 58, 'Female', 'Manager')
('D2_177', 58, 'Male', 'Software Engineer')
('D2_224', 58, 'Female', 'Researcher')
('D2_249', 58, 'Male', 'Designer')
('D2_274', 58, 'Male', 'Software Engineer')
('D2_312', 58, 'Female', 'Doctor')
('D2_479', 58, 'Male', 'Student')
('D2_507', 58, 'Male', 'Freelancer')
('D2_517', 58, 'Male', 'Manager')
('D2_586', 58, 'Female', 'Designer')
('D2_607', 58, 'Male', 'Software Engineer')
('D2_633', 58, 'Female', 'Student')
('D2_666', 58, 'Other', 'Manager')
('D2_774', 58, 'Male', 'Manager')
('D2_826', 58, 'Female', 'Freelancer')
('D2_835', 58, 'Female', 'Researcher')
('D2_931', 58, 'Male', 'Teacher')
('D2_1042', 58, 'Male', 'Manager')
('D2_1060', 58, 'Female', 'Manager')
('D2_1087', 58, 'Male', 'Doctor')
('D2_1213', 58, 'Female', 'Student')
('D2_1305', 58, 'Male', 'Manager')
('D2_1408', 58, 'Female', 'Designer')
('D2_1434', 58, 'Female', 'Researcher')
('D2_1482', 58, 'Female', 'Student')
('D2_1511', 58, 'Male', 'Teacher')
('D2_1523', 58, 'Female', 'Teacher')
('D2_1570', 58, 'Male', 'Freelancer')
('D2_1649', 58, 'Other', 'Designer')
('D2_1654', 58, 'Male', 'Manager')
('D2_1671', 58, 'Male', 'Freelancer')
('D2_1696', 58, 'Male', 'Teacher')
('D2_1711', 58, 'Male', 'Teacher')
('D2_1733', 58, 'Male', 'Researcher')
('D2_1754', 58, 'Other', 'Software Engineer')
('D2_1785', 58, 'Male', 'Designer')
('D2_1816', 58, 'Male', 'Freelancer')
('D2_1893', 58, 'Female', 'Doctor')
('D2_1900', 58, 'Female', 'Doctor')
('D2_1906', 58, 'Male', 'Software Engineer')
('D2_1918', 58, 'Male', 'Doctor')
('D2_2072', 58, 'Female', 'Doctor')
('D2_2093', 58, 'Female', 'Designer')
('D2_2164', 58, 'Female', 'Manager')
('D2_2222', 58, 'Female', 'Student')
('D2_2323', 58, 'Female', 'Teacher')
('D2_2331', 58, 'Male', 'Doctor')
('D2_2334', 58, 'Male', 'Teacher')
('D2_2399', 58, 'Other', 'Student')
('D2_2400', 58, 'Male', 'Student')
('D2_2438', 58, 'Male', 'Doctor')
('D2_2499', 58, 'Female', 'Freelancer')
('D2_2610', 58, 'Female', 'Doctor')
('D2_2670', 58, 'Male', 'Software Engineer')
('D2_2681', 58, 'Male', 'Freelancer')
('D2_2722', 58, 'Male', 'Researcher')
('D2_2745', 58, 'Female', 'Software Engineer')
('D2_2828', 58, 'Male', 'Researcher')
('D2_2918', 58, 'Female', 'Software Engineer')
('D2_2921', 58, 'Female', 'Software Engineer')
('D2_2927', 58, 'Female', 'Manager')
('D2_2929', 58, 'Male', 'Freelancer')
('D2_2958', 58, 'Male', 'Software Engineer')
('D2_2981', 58, 'Female', 'Researcher')
('D2_3014', 58, 'Female', 'Designer')
('D2_3018', 58, 'Male', 'Software Engineer')
('D2_3023', 58, 'Female', 'Manager')
('D2_3065', 58, 'Male', 'Freelancer')
('D2_3069', 58, 'Male', 'Designer')
('D2_3093', 58, 'Female', 'Doctor')
('D2_3120', 58, 'Female', 'Software Engineer')
('D2_3188', 58, 'Male', 'Software Engineer')
('D2_3238', 58, 'Male', 'Manager')
('D2_3288', 58, 'Male', 'Designer')
('D2_3362', 58, 'Male', 'Student')
('D2_3398', 58, 'Female', 'Researcher')
('D2_3412', 58, 'Female', 'Designer')
('D2_3464', 58, 'Female', 'Software Engineer')
('D2_3469', 58, 'Male', 'Software Engineer')
('D2_3471', 58, 'Male', 'Researcher')
('D2_3541', 58, 'Female', 'Freelancer')
('D2_3571', 58, 'Male', 'Software Engineer')
('D2_3592', 58, 'Female', 'Student')
('D2_3613', 58, 'Male', 'Student')
('D2_3617', 58, 'Male', 'Designer')
('D2_3649', 58, 'Male', 'Doctor')
('D2_3743', 58, 'Male', 'Freelancer')
('D2_3744', 58, 'Male', 'Doctor')
('D2_3750', 58, 'Male', 'Doctor')
('D2_3774', 58, 'Male', 'Student')
('D2_3801', 58, 'Female', 'Researcher')
('D2_3818', 58, 'Female', 'Researcher')
('D2_3856', 58, 'Male', 'Student')
('D2_3869', 58, 'Male', 'Teacher')
('D2_3947', 58, 'Female', 'Designer')
('D2_3970', 58, 'Female', 'Researcher')
('D2_3980', 58, 'Male', 'Software Engineer')
('D2_3985', 58, 'Female', 'Manager')
('D2_4007', 58, 'Male', 'Doctor')
('D2_4025', 58, 'Female', 'Researcher')
('D2_4075', 58, 'Female', 'Student')
('D2_4181', 58, 'Female', 'Doctor')
('D2_4272', 58, 'Female', 'Freelancer')
('D2_4273', 58, 'Male', 'Teacher')
('D2_4280', 58, 'Female', 'Student')
('D2_4501', 58, 'Male', 'Teacher')
('D2_4503', 58, 'Male', 'Manager')
('D2_4713', 58, 'Male', 'Manager')
('D2_4803', 58, 'Male', 'Researcher')
('D2_4828', 58, 'Male', 'Software Engineer')
('D2_4872', 58, 'Female', 'Software Engineer')
('D2_5079', 58, 'Male', 'Designer')
('D2_5100', 58, 'Male', 'Teacher')
('D2_5116', 58, 'Female', 'Manager')
('D2_5301', 58, 'Male', 'Freelancer')
('D2_5308', 58, 'Male', 'Researcher')
('D2_5389', 58, 'Female', 'Student')
('D2_5516', 58, 'Male', 'Teacher')
('D2_5548', 58, 'Female', 'Researcher')
('D2_5586', 58, 'Male', 'Designer')
('D2_5704', 58, 'Male', 'Student')
('D2_5718', 58, 'Male', 'Student')
('D2_5765', 58, 'Female', 'Teacher')
('D2_5798', 58, 'Male', 'Designer')
('D2_5836', 58, 'Female', 'Teacher')
('D2_5839', 58, 'Male', 'Student')
('D2_5884', 58, 'Female', 'Freelancer')
('D2_5917', 58, 'Male', 'Freelancer')
('D2_5968', 58, 'Female', 'Freelancer')
('D2_6039', 58, 'Female', 'Software Engineer')
('D2_6045', 58, 'Female', 'Software Engineer')
('D2_6070', 58, 'Male', 'Freelancer')
('D2_6122', 58, 'Male', 'Teacher')
('D2_6152', 58, 'Female', 'Teacher')
('D2_6208', 58, 'Male', 'Teacher')
('D2_6264', 58, 'Female', 'Freelancer')
('D2_6301', 58, 'Male', 'Teacher')
('D2_6302', 58, 'Female', 'Doctor')
('D2_6310', 58, 'Male', 'Software Engineer')
('D2_6329', 58, 'Male', 'Manager')
('D2_6350', 58, 'Other', 'Doctor')
('D2_6434', 58, 'Male', 'Manager')
('D2_6527', 58, 'Male', 'Teacher')
('D2_6694', 58, 'Male', 'Researcher')
('D2_6750', 58, 'Female', 'Doctor')
('D2_6779', 58, 'Male', 'Doctor')
('D2_6783', 58, 'Female', 'Doctor')
('D2_6865', 58, 'Female', 'Freelancer')
('D2_6922', 58, 'Male', 'Teacher')
('D2_7063', 58, 'Male', 'Manager')
('D2_7126', 58, 'Female', 'Student')
('D2_7142', 58, 'Female', 'Student')
('D2_7165', 58, 'Male', 'Freelancer')
('D2_7212', 58, 'Male', 'Designer')
('D2_7333', 58, 'Female', 'Manager')
('D2_7359', 58, 'Male', 'Researcher')
('D2_7389', 58, 'Female', 'Freelancer')
('D2_7424', 58, 'Female', 'Manager')
('D2_7437', 58, 'Male', 'Teacher')
('D2_7464', 58, 'Male', 'Software Engineer')
('D2_7489', 58, 'Female', 'Freelancer')
('D2_7572', 58, 'Other', 'Teacher')
('D2_7630', 58, 'Male', 'Manager')

In [ ]:
#Count how many of each gender description are in d1
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT gender, COUNT(*) FROM users_d1 GROUP BY gender;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

('Female', 2183)
('Male', 2284)
('Other', 2214)

In [171]:
#Count how many of each gender description are in d2
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT gender, COUNT(*) FROM users_d2 GROUP BY gender;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

('Female', 7181)
('Male', 7234)
('Other', 585)

In [ ]:
#What is the average screen time based on gender for d1?
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT u.gender, AVG(h.daily_screen_time_hours) AS avg_hours
        FROM users_d1 u
        JOIN hours_d1 h on u.user_id = h.user_id
        GROUP BY u.gender;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

('Female', 7.820398534127348)
('Male', 7.915971978984239)
('Other', 7.855975609756098)

In [175]:
#What is the average screen time based on gender for d2?
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT u.gender, AVG(h.daily_screen_time_hours) AS avg_hours
        FROM users_d2 u
        JOIN hours_d2 h on u.user_id = h.user_id
        GROUP BY u.gender;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

('Female', 5.487157777468319)
('Male', 5.5080273707492395)
('Other', 5.597555555555556)

In [177]:
# What is the average screen time based on age for d1?

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT u.age, AVG(h.daily_screen_time_hours) AS avg_hours
        FROM users_d1 u
        JOIN hours_d1 h ON u.user_id = h.user_id
        GROUP BY u.age
        ORDER BY avg_hours DESC;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

(21, 8.059445843828716)
(26, 8.050103092783505)
(35, 8.035437665782494)
(29, 7.985406824146982)
(28, 7.9784146341463416)
(33, 7.9253562005277045)
(22, 7.911048158640226)
(31, 7.89707729468599)
(19, 7.880085959885387)
(34, 7.856951871657754)
(32, 7.8419845360824745)
(20, 7.781450777202072)
(25, 7.776145251396648)
(27, 7.7641351351351355)
(23, 7.743567567567568)
(24, 7.708775510204082)
(18, 7.686388888888889)
(30, 7.6496721311475415)

In [178]:
# What is the average screen time based on age for d1?

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT u.age, AVG(h.daily_screen_time_hours) AS avg_hours
        FROM users_d2 u
        JOIN hours_d2 h ON u.user_id = h.user_id
        GROUP BY u.age
        ORDER BY avg_hours DESC;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

(56, 5.764917582417582)
(27, 5.7252023121387285)
(57, 5.6784302325581395)
(18, 5.635295857988166)
(35, 5.633045822102426)
(50, 5.6298295454545455)
(40, 5.615569948186529)
(43, 5.613225806451613)
(22, 5.591715976331361)
(44, 5.586319018404908)
(25, 5.578374655647383)
(52, 5.571331444759207)
(55, 5.5625217391304345)
(37, 5.561228571428572)
(51, 5.559230769230769)
(46, 5.5401639344262295)
(24, 5.539756097560976)
(34, 5.534949748743718)
(30, 5.5268434343434345)
(42, 5.526164772727273)
(38, 5.509051490514905)
(48, 5.499287925696595)
(58, 5.492529411764706)
(59, 5.490389972144847)
(49, 5.488679775280899)
(39, 5.469413333333334)
(21, 5.458422535211268)
(45, 5.453532467532468)
(28, 5.447371601208459)
(36, 5.437173913043479)
(33, 5.434468085106383)
(32, 5.424308510638298)
(23, 5.415555555555556)
(26, 5.414770114942528)
(29, 5.405536723163841)
(53, 5.391310541310541)
(19, 5.382444444444444)
(31, 5.364456824512534)
(47, 5.341107784431138)
(54, 5.340246575342466)
(41, 5.227346368715084)
(20, 5.198314285714286)

In [179]:
#How many users are in each age group in d1?

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT age, COUNT(*)
        FROM users_d1
        GROUP BY age
        ORDER BY age;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

(18, 360)
(19, 349)
(20, 386)
(21, 397)
(22, 353)
(23, 370)
(24, 343)
(25, 358)
(26, 388)
(27, 370)
(28, 328)
(29, 381)
(30, 366)
(31, 414)
(32, 388)
(33, 379)
(34, 374)
(35, 377)

In [180]:
#How many users are in each age group in d2?

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT age, COUNT(*)
        FROM users_d2
        GROUP BY age
        ORDER BY age;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

(18, 338)
(19, 360)
(20, 350)
(21, 355)
(22, 338)
(23, 351)
(24, 328)
(25, 363)
(26, 348)
(27, 346)
(28, 331)
(29, 354)
(30, 396)
(31, 359)
(32, 376)
(33, 376)
(34, 398)
(35, 371)
(36, 368)
(37, 350)
(38, 369)
(39, 375)
(40, 386)
(41, 358)
(42, 352)
(43, 403)
(44, 326)
(45, 385)
(46, 366)
(47, 334)
(48, 323)
(49, 356)
(50, 352)
(51, 338)
(52, 353)
(53, 351)
(54, 365)
(55, 345)
(56, 364)
(57, 344)
(58, 340)
(59, 359)

In [182]:
#What is the average number of notifications per day by gender in d1?

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT u.gender, AVG(b.notifications_per_day)
        FROM users_d1 u
        JOIN behavior_d1 b 
        ON u.user_id = b.user_id
        GROUP BY u.gender;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

('Female', 133.6051305542831)
('Male', 135.34676007005254)
('Other', 133.73712737127371)

In [183]:
#What is the average number of notifications per day by gender in d2?

with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute("""
        SELECT u.gender, AVG(w.notifications_received_per_day)
        FROM users_d2 u
        JOIN wellbeing_d2 w 
        ON u.user_id = w.user_id
        GROUP BY u.gender;
        """)

    rows = cursor.fetchall()

    for row in rows:
        print(row)

('Female', 160.40036206656455)
('Male', 161.52944429084877)
('Other', 159.00512820512822)