In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt
import numpy as np

In [4]:
import sqlite3

In [5]:
df1 = pd.read_csv('cleaned_smartphone_usage_and_addiction.csv')
df2 = pd.read_csv('cleaned_sleep_mobile_stress_dataset_15000.csv')

In [6]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users_d1 (
            user_id TEXT PRIMARY KEY,
            age     INTEGER,
            gender  TEXT NOT NULL
        );
    """)

    connection.commit()

In [7]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users',), ('users_d1',)]

In [8]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(users_d1)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 0, None, 1), (1, 'age', 'INTEGER', 0, None, 0), (2, 'gender', 'TEXT', 1, None, 0)]

In [9]:
with sqlite3.connect('Smartphone.db')as connection:
    cursor = connection.cursor()

    cursor.execute("DROP TABLE users;")

    connection.commit()

In [11]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',)]

In [12]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(users_d1)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 0, None, 1), (1, 'age', 'INTEGER', 0, None, 0), (2, 'gender', 'TEXT', 1, None, 0)]

In [13]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS behavior_d1 (
            user_id                     TEXT FORGEIN KEY,
            notifications_per_day       INTEGER,
            app_opens_per_day           INTEGER,
            stress_level                TEXT NOT NULL,
            addiction_level             TEXT NOT NULL,
            addicted_label              TEXT NOT NULL
        );
    """)

    connection.commit()

In [14]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',)]

In [15]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(behavior_d1)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT FORGEIN KEY', 0, None, 0), (1, 'notifications_per_day', 'INTEGER', 0, None, 0), (2, 'app_opens_per_day', 'INTEGER', 0, None, 0), (3, 'stress_level', 'TEXT', 1, None, 0), (4, 'addiction_level', 'TEXT', 1, None, 0), (5, 'addicted_label', 'TEXT', 1, None, 0)]

In [ ]:
#with sqlite3.connect('Smartphone.db') as connection:
        #cursor = connection.cursor()

        #cursor.execute('DROP TABLE behavior_d1;')
       # connection.commit()

In [17]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',)]

In [18]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS behavior_d1 (
            user_id                     TEXT NOT NULL,
            notifications_per_day       INTEGER,
            app_opens_per_day           INTEGER,
            stress_level                TEXT NOT NULL,
            addiction_level             TEXT NOT NULL,
            addicted_label              TEXT NOT NULL
        );
    """)

    connection.commit()

In [19]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(behavior_d1)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 1, None, 0), (1, 'notifications_per_day', 'INTEGER', 0, None, 0), (2, 'app_opens_per_day', 'INTEGER', 0, None, 0), (3, 'stress_level', 'TEXT', 1, None, 0), (4, 'addiction_level', 'TEXT', 1, None, 0), (5, 'addicted_label', 'TEXT', 1, None, 0)]

In [20]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS hours_d1 (
            user_id                     TEXT NOT NULL,
            daily_screen_time_hours     REAL,
            social_media_hours          REAL,
            gaming_hours                REAL,
            work_study_hours            REAL,
            sleep_hours                 REAL,
            weekend_screen_time         REAL
        );
    """)

    connection.commit()

In [21]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',)]

In [22]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(hours_d1)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 1, None, 0), (1, 'daily_screen_time_hours', 'REAL', 0, None, 0), (2, 'social_media_hours', 'REAL', 0, None, 0), (3, 'gaming_hours', 'REAL', 0, None, 0), (4, 'work_study_hours', 'REAL', 0, None, 0), (5, 'sleep_hours', 'REAL', 0, None, 0), (6, 'weekend_screen_time', 'REAL', 0, None, 0)]

In [23]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users_d2 (
            user_id     TEXT NOT NULL,
            age         INTEGER,
            gender      TEXT NOT NULL,
            occupation  TEXT NOT NULL
        );
    """)

    connection.commit()

In [24]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',), ('users_d2',)]

In [28]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(users_d2)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 1, None, 0), (1, 'age', 'INTEGER', 0, None, 0), (2, 'gender', 'TEXT', 1, None, 0), (3, 'occupation', 'TEXT', 1, None, 0)]

In [30]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS wellbeing_d2 (
            user_id                         TEXT NOT NULL,
            sleep_quality_score             REAL,
            stress_level                    REAL,
            caffeine_intake_cups            INTEGER,
            physical_activity_minutes       INTEGER,
            notifications_received_per_day  INTEGER,
            mental_fatigue_score            REAL,
            stress_level_rank               TEXT NOT NULL,
            screen_time_category            TEXT NOT NULL
        );
    """)

    connection.commit()

In [31]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',), ('users_d2',), ('wellbeing_d2',)]

In [32]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(wellbeing_d2)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 1, None, 0), (1, 'sleep_quality_score', 'REAL', 0, None, 0), (2, 'stress_level', 'REAL', 0, None, 0), (3, 'caffeine_intake_cups', 'INTEGER', 0, None, 0), (4, 'physical_activity_minutes', 'INTEGER', 0, None, 0), (5, 'notifications_received_per_day', 'INTEGER', 0, None, 0), (6, 'mental_fatigue_score', 'REAL', 0, None, 0), (7, 'stress_level_rank', 'TEXT', 1, None, 0), (8, 'screen_time_category', 'TEXT', 1, None, 0)]

In [33]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute("""
        CREATE TABLE IF NOT EXISTS hours_d2 (
            user_id                             TEXT NOT NULL,
            daily_screen_time_hours             REAL,
            phone_usage_before_sleep_minutes    INTEGER,
            sleep_duration_hours                REAL
        );
    """)

    connection.commit()

In [34]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    print(cursor.fetchall())

[('users_d1',), ('behavior_d1',), ('hours_d1',), ('users_d2',), ('wellbeing_d2',), ('hours_d2',)]

In [35]:
with sqlite3.connect('Smartphone.db') as connection:
    cursor = connection.cursor()

    cursor.execute('PRAGMA table_info(wellbeing_d2)')
    print(cursor.fetchall())

[(0, 'user_id', 'TEXT', 1, None, 0), (1, 'sleep_quality_score', 'REAL', 0, None, 0), (2, 'stress_level', 'REAL', 0, None, 0), (3, 'caffeine_intake_cups', 'INTEGER', 0, None, 0), (4, 'physical_activity_minutes', 'INTEGER', 0, None, 0), (5, 'notifications_received_per_day', 'INTEGER', 0, None, 0), (6, 'mental_fatigue_score', 'REAL', 0, None, 0), (7, 'stress_level_rank', 'TEXT', 1, None, 0), (8, 'screen_time_category', 'TEXT', 1, None, 0)]

In [36]:
users_d1 = df1[
    [
        'user_id',
        'age',
        'gender'
    ]
]

In [37]:
users_d1.head()

     user_id  age gender
0  D1_U00003   31  Other
1  D1_U00004   32  Other
2  D1_U00005   25   Male
3  D1_U00006   26   Male
4  D1_U00007   25   Male

In [38]:
with sqlite3.connect('Smartphone.db') as connection:
    users_d1.to_sql(
        'users_d1',
        connection,
        if_exists='append',
        index=False
    )

In [39]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM users_d1')
    print(cursor.fetchone())

(6681,)

In [41]:
behavior_d1 = df1[
    [
        'user_id',
        'notifications_per_day',
        'app_opens_per_day',
        'stress_level',
        'addiction_level',
        'addicted_label'
    ]
]

In [42]:
behavior_d1.head()

,user_id,notifications_per_day,app_opens_per_day,stress_level,addiction_level,addicted_label
0,D1_U00003,44,106,High,Mild,No
1,D1_U00004,178,107,High,Moderate,Yes
2,D1_U00005,136,177,Low,Severe,Yes
3,D1_U00006,82,56,Medium,Severe,Yes
4,D1_U00007,165,95,Medium,Severe,Yes

In [44]:
with sqlite3.connect('Smartphone.db') as connection:
    behavior_d1.to_sql(
        'behavior_d1',
        connection,
        if_exists='append',
        index=False
    )

In [45]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM behavior_d1')
    print(cursor.fetchone())

(6681,)

In [47]:
hours_d1 = df1[
    [
        'user_id',
        'daily_screen_time_hours',
        'social_media_hours',
        'gaming_hours',
        'work_study_hours',
        'sleep_hours',
        'weekend_screen_time'
    ]
]

In [48]:
hours_d1.head()

,user_id,daily_screen_time_hours,social_media_hours,gaming_hours,work_study_hours,sleep_hours,weekend_screen_time
0,D1_U00003,6.06,1.36,3.83,2.35,4.92,8.68
1,D1_U00004,7.83,5.85,1.51,3.54,8.23,9.77
2,D1_U00005,9.96,5.92,3.42,5.27,6.21,12.55
3,D1_U00006,9.32,4.26,0.29,3.99,6.90,10.98
4,D1_U00007,10.40,4.93,1.60,0.86,8.61,11.43

In [49]:
with sqlite3.connect('Smartphone.db') as connection:
    hours_d1.to_sql(
        'hours_d1',
        connection,
        if_exists='append',
        index=False
    )

In [50]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM hours_d1')
    print(cursor.fetchone())

(6681,)

In [51]:
users_d2 = df2[
    [
        'user_id',
        'age',
        'gender',
        'occupation'
    ]
]

In [52]:
users_d2.head()

  user_id  age  gender         occupation
0    D2_1   56  Female           Designer
1    D2_2   46  Female            Teacher
2    D2_3   32  Female           Designer
3    D2_4   25    Male  Software Engineer
4    D2_5   38  Female            Teacher

In [54]:
with sqlite3.connect('Smartphone.db') as connection:
    users_d2.to_sql(
        'users_d2',
        connection,
        if_exists='append',
        index=False
    )

In [55]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM users_d2')
    print(cursor.fetchone())

(15000,)

In [56]:
wellbeing_d2 = df2[
    [
        'user_id',
        'sleep_quality_score',
        'stress_level',
        'caffeine_intake_cups',
        'physical_activity_minutes',
        'notifications_received_per_day',
        'mental_fatigue_score',
        'stress_level_rank',
        'screen_time_category'
    ]
]

In [57]:
wellbeing_d2.head()

,user_id,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score,stress_level_rank,screen_time_category
0,D2_1,7.72,3.49,0,35,119,3.57,Medium,Moderate
1,D2_2,9.70,3.01,0,16,299,1.91,Low,Low
2,D2_3,6.38,5.03,0,17,21,6.05,Medium,Moderate
3,D2_4,5.53,10.00,0,3,220,9.92,High,High
4,D2_5,6.69,6.71,4,92,167,5.99,High,Moderate

In [58]:
with sqlite3.connect('Smartphone.db') as connection:
    wellbeing_d2.to_sql(
        'wellbeing_d2',
        connection,
        if_exists='append',
        index=False
    )

In [59]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM wellbeing_d2')
    print(cursor.fetchone())

(15000,)

In [60]:
hours_d2 = df2[
    [
        'user_id',
        'daily_screen_time_hours',
        'phone_usage_before_sleep_minutes',
        'sleep_duration_hours'
    ]
]

In [61]:
hours_d2.head()

,user_id,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours
0,D2_1,3.26,86,5.31
1,D2_2,1.85,32,7.36
2,D2_3,3.04,107,4.50
3,D2_4,9.00,36,6.68
4,D2_5,3.52,56,7.57

In [62]:
with sqlite3.connect('Smartphone.db') as connection:
    hours_d2.to_sql(
        'hours_d2',
        connection,
        if_exists='append',
        index=False
    )

In [63]:
with sqlite3.connect("Smartphone.db") as connection:
    cursor = connection.cursor()

    cursor.execute('SELECT COUNT(*) FROM hours_d2')
    print(cursor.fetchone())

(15000,)